---
sidebar: sidebar 
permalink: Management.System_Administration.configure_antivirus.html 
summary: 바이러스 백신 고려 사항 
keywords:  
---
= Monitoring and Antivirus를 적용합니다




== 개요

VDS(가상 데스크톱 서비스) 관리자는 플랫폼 인프라(최소 CWMGR1로 구성) 및 기타 모든 인프라 및 VM(가상 머신)을 모두 모니터링할 책임이 있습니다. 대부분의 경우 관리자는 데이터 센터/IaaS 공급자와 함께 인프라스트럭처(하이퍼바이저/SAN) 모니터링을 직접 정렬합니다. 관리자는 일반적으로 선호하는 원격 관리 및 모니터링(RMM) 솔루션을 배포하여 터미널 서버 및 데이터 서버를 모니터링할 책임이 있습니다.

안티바이러스(Anti-Virus)는 관리자의 책임입니다(플랫폼 인프라 및 터미널/데이터 서버 VM 모두 해당). 이 프로세스를 간소화하기 위해 Azure 서버용 VDS에는 기본적으로 Windows Defender가 적용됩니다.


NOTE: 타사 솔루션을 설치할 때 VDS 자동화를 방해할 수 있는 방화벽 또는 기타 구성 요소를 포함하지 마십시오.

보다 구체적으로, 매우 구체적인 안티바이러스 정책이 기본적으로 적용되는 경우 이러한 안티바이러스 에이전트가 Virtual Desktop Service에서 관리하는 서버에 설치될 때 부작용이 발생할 수 있습니다.

전체 지침은 VDS 플랫폼 자동화는 일반적으로 안티바이러스 또는 안티맬웨어 제품의 영향을 받지 않지만 모든 플랫폼 서버(CWMGR1, RDGateways, HTML5Gateways, FTP 등)에서 다음 프로세스에 대한 예외/예외를 추가하는 것이 가장 좋은 방법입니다.

....
*\paexec.exe
*\paexec_1_25.exe
C:\Program Files\CloudWorkspace\CwAgent\CwAgent.exe
C:\Program Files\CloudWorkspace\CW Automation Service\cw.automation.service.exe
C:\Program Files\CloudWorkspace\CwVmAutomationService\CwVmAutomationService.exe
C:\Program Files (x86)\Myrtille\bin\Myrtille.Printer.exe
C:\Program Files (x86)\Myrtille\bin\Myrtille.Services.exe
....
또한 클라이언트 서버에서 다음 프로세스를 안전하게 나열하는 것이 좋습니다.

....
C:\Program Files\CloudWorkspace\CwAgent\paexec.exe
C:\Program Files\CloudWorkspace\CwAgent\CwAgent.exe
C:\Program Files\CloudWorkspace\CwRemoteApps\cwra.exe
C:\Program Files\CloudWorkspace\Pen\Pen.exe
C:\Program Files\CloudWorkspace\MfaAgent\MFAAgent.exe
C:\Program Files\CloudWorkspace\MfaAgent\MFAAgentMonitor.exe
....