---
sidebar: sidebar 
permalink: Reference.Release_Notes.vds_v6.0_release_notes.html 
summary: NetApp VDS 릴리즈 노트 v6.0 
keywords:  
---
= Virtual Desktop Service – v6.0 릴리즈 노트




== VDS V6 릴리스: 2022년 2월 3일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2022 년 2월 3일 목요일 오후 10시부터 오후 11시까지 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* VDM에 대한 프로필 로밍 검색 기능이 향상되었습니다
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS V6 릴리스: 2022년 1월 20일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6 _ 시기: _ 2022 년 1월 20일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스가 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* ACE(Azure Cost Estimator)의 링크 리디렉션 문제에 대한 버그 수정
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS V6 릴리스: 2022년 1월 6일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2022 년 1월 6일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스가 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 파트너와 하위 파트너 모두를 위한 셀프 서비스 암호 재설정 보고서를 소개합니다
* 배포 프로세스 시작 시 고유한 Azure 인증 문제에 대한 버그 수정.




== VDS V6 릴리스: 2021년 12월 16일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 12월 16일 목요일 오후 10시부터 오후 11시까지 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 기본 SMS 공급자를 사용할 수 없는 경우 MFA에 대한 보조 SMS 메시지 전송 기능 향상
* Windows용 VDS 클라이언트에 사용되는 인증서로 업데이트합니다




== VDS V6 릴리스: 2021년 12월 2일 목요일 - 변경 계획 없음

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 12월 2일 목요일 오후 10시 – 오후 11시 Eastern_Impact: _ 없음



== VDS V6 핫픽스: 2021년 11월 18일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 11월 18일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* AAD가 AADDS 기반인 PAM 문제에 대한 버그 수정




== VDS V6 핫픽스: 2021년 11월 8일 월요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6 _ 시기: _ 2021년 11월 8일 월요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 모든 사용자에 대해 VDS UI에서 채팅 상자를 활성화합니다
* 배포 선택 항목의 고유한 조합에 대한 버그 수정




== VDS V6 릴리스: 2021년 11월 7일 일요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6 _ 시기: _ 2021년 11월 7일 일요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* FSLogix 프로필의 자동 축소를 해제하는 Command Center 옵션을 소개합니다
* AADDS(Azure Active Directory Domain Services)를 활용하는 배포 시 PAM에 대한 버그 수정
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




=== Azure 비용 추정기

* 다양한 지역에서 업데이트된 서비스를 이용할 수 있습니다




== VDS V6 릴리스: 2021년 10월 21일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 10월 21일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* FSLogix 프로필의 자동 축소를 해제하는 Command Center 옵션을 소개합니다
* FSLogix 프로필이 마운트된 위치를 보여 주는 야간 보고서가 개선되었습니다
* Azure US South Central 영역에서 CWMGR1(플랫폼 VM)에 사용되는 기본 VM 시리즈/크기를 D2S v4로 업데이트합니다




== VDS V6 릴리스: 2021년 10월 7일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 10월 7일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 특정 프로비저닝 컬렉션 구성이 제대로 저장되지 않는 시나리오에 대한 버그 수정




== VDS V6 릴리스: 2021년 9월 23일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 9월 23일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* AADDS 기반 배포와 통합하기 위해 PAM에 대한 업데이트
* 비 AVD 배포에 대한 작업 영역 모듈에 RemoteApp URL을 표시합니다
* 특정 온-프레미스 Active Directory 구성에서 최종 사용자를 관리자로 만드는 시나리오에 대한 버그 수정




== VDS V6 릴리스: 2021년 9월 9일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 9월 9일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS V6 릴리스: 2021년 8월 26일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 8월 26일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* VDS 관리 UI에 대한 액세스 권한이 부여되면 사용자 데스크톱에 있는 URL로 업데이트합니다




== VDS V6 릴리스: 2021년 8월 12일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 8월 12일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* Cloud Insights 기능 및 컨텍스트의 향상된 기능
* 백업 스케줄 빈도 처리 개선
* 버그 수정 - 서비스 재시작 시 CwVmAutomation 서비스 검사 구성에 대한 문제를 해결합니다
* 버그 수정 - 특정 시나리오에서 구성을 저장할 수 없는 DCConifg 관련 문제를 해결합니다
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS V6 핫픽스: 2021년 7월 30일 화요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 7월 30일 금요일 오후 7시~오후 8시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 자동화를 더욱 쉽게 개선할 수 있는 배포 템플릿 업데이트




== VDS V6 릴리스: 2021년 7월 29일 목요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 7월 29일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 버그 수정 - CWAgent가 의도한 대로 설치되지 않은 VMware 배포 문제를 해결합니다
* 버그 수정 - 데이터 역할이 지정된 서버를 생성해도 제대로 작동하지 않는 VMware 배포 문제를 해결합니다




== VDS V6 핫픽스: 2021년 7월 20일 화요일

_ 구성 요소: _ 가상 데스크톱 서비스 v6_when: _ 2021년 7월 20일 화요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 특정 구성에서 비정상적으로 많은 양의 API 트래픽을 일으키는 문제를 해결합니다




== VDS 6.0 릴리스: 2021년 7월 15일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 7월 15일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* Cloud Insights 통합 기능 향상 – 사용자별 성능 메트릭을 캡처하여 사용자 컨텍스트에 표시합니다
* ANF 프로비저닝 자동화 개선 – 고객의 Azure 테넌트에서 공급자로서 NetApp을 자동으로 등록하는 기능이 향상되었습니다
* 새 AVD 작업 공간을 만들 때 구문 조정
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS 6.0 릴리스: 2021년 6월 24일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 6월 4일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.


NOTE: 7월 4일경에 일정이 잡기때문에 다음 VDS 릴리스는 목요일 7월 15일에 출시될 예정입니다.



=== 가상 데스크톱 서비스

* Windows 가상 데스크톱(WVD)이 이제 Azure 가상 데스크톱(AVD)임을 반영하는 업데이트
* Excel 내보내기의 사용자 이름 형식 버그 수정
* 사용자 지정 브랜드의 HTML5 로그인 페이지를 위한 향상된 구성
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




=== 비용 추정기

* Windows 가상 데스크톱(WVD)이 이제 Azure 가상 데스크톱(AVD)임을 반영하는 업데이트
* 새로운 지역에서 더 많은 서비스/GPU VM을 사용할 수 있음을 반영하는 업데이트가 있습니다




== VDS 6.0 릴리스: 2021년 6월 10일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 6월 10일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 추가 HTML5 브라우저 기반 게이트웨이/VM 액세스 포인트 도입
* 호스트 풀을 삭제한 후 사용자 라우팅이 개선되었습니다
* 관리되지 않는 호스트 풀을 가져오는 것이 예상대로 작동하지 않는 시나리오에 대한 버그 수정
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS 6.0 릴리스: 2021년 6월 10일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 6월 10일 목요일 오후 10시 동부 지역 _ 영향: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 기술적 개선 사항:

* 각 VM에 설치된 .NET Framework 버전을 v4.7.2에서 v4.8.0으로 업데이트합니다
* 로컬 제어 플레인 팀과 다른 모든 엔터티 간에 https:// 및 TLS 1.2 이상을 사용하는 추가적인 백엔드 적용
* Command Center에서 백업 삭제 작업에 대한 버그 수정 – CWMGR1의 표준 시간대를 올바르게 참조합니다
* 명령 센터 작업의 이름을 Azure 파일 공유에서 Azure 파일 공유로 변경합니다
* Azure 공유 이미지 갤러리의 명명 규칙 업데이트
* 동시 사용자 로그인 수 수집 기능이 향상되었습니다
* CWMGR1 VM에서 트래픽 아웃바운드를 제한하는 경우 CWMGR1에서 허용되는 아웃바운드 트래픽으로 업데이트합니다
* CWMGR1에서 아웃바운드 트래픽을 제한하지 않는 경우 여기에서 업데이트할 필요가 없습니다
* CWMGR1에서 아웃바운드 트래픽을 제한하는 경우 vdctoolsapiprimary.azurewebsites.net 액세스를 허용하십시오. 참고: 더 이상 vdctoolsapi.trafficmanager.net 액세스를 허용할 필요가 없습니다.




=== 배포 개선 사항:

* 서버 이름에 사용자 지정 접두사를 향후 지원하기 위한 기반을 마련합니다
* Azure 배포의 프로세스 자동화 및 중복성이 향상되었습니다
* Google Cloud Platform 구축을 위한 수많은 구축 자동화 개선 사항
* Google Cloud Platform 배포에서 Windows Server 2019를 지원합니다
* Windows 10 20H2 EVD 이미지가 있는 일부 시나리오에 대한 버그 수정




=== 서비스 제공 개선 사항:

* Cloud Insights 통합을 도입하여 사용자 환경, VM 및 스토리지 계층을 위한 스트리밍 성능 데이터를 제공합니다
* 에서는 최근에 방문한 VDS 페이지로 빠르게 탐색할 수 있는 기능을 제공합니다
* Azure 구축 시 목록(사용자, 그룹, 서버, 애플리케이션 등)의 로드 시간이 크게 향상되었습니다
* 사용자, 그룹, 서버, 관리자, 보고서 목록을 쉽게 내보낼 수 있는 기능을 소개합니다. 등
* 고객에 대해 VDS MFA 방법을 사용할 수 있는 방법을 제어하는 기능을 소개합니다(고객이 선호하는 이메일보다 선호함) SMS, 예:)
* VDS 셀프 서비스 암호 재설정 이메일에 대한 사용자 정의 가능한 "보낸 사람" 필드를 소개합니다
* VDS 셀프 서비스 암호 재설정 이메일만 지정된 도메인(회사 소유 vs 개인, 예:)
* 에서는 사용자에게 전자 메일을 계정에 추가하라는 메시지를 표시할 수 있는 업데이트 또는 MFA/셀프 서비스 암호 재설정을 사용할 수 있습니다
* 중지된 배포를 시작할 때 배포 내의 모든 VM도 시작합니다
* 새로 생성된 Azure VM에 할당할 IP 주소를 결정하는 성능 향상




== VDS 6.0 릴리스: 2021년 5월 27일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 5월 27일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* AVD 호스트 풀의 풀링된 세션 호스트에 대한 Connect 시작 을 소개합니다
* Cloud Insights 통합을 통해 사용자 성능 메트릭을 소개합니다
* 작업 영역 모듈에서 서버 탭을 더 두드러지게 표시합니다
* VM이 VDS에서 삭제된 경우 Azure Backup을 통해 VM 복원을 허용합니다
* 서버에 연결 기능의 향상된 처리
* 인증서를 자동으로 생성 및 업데이트할 때 변수 처리 기능이 향상되었습니다
* 드롭다운 메뉴에서 X를 클릭해도 선택 항목이 예상대로 지워지지 않는 문제에 대한 버그 수정
* SMS 메시지 프롬프트의 안정성 및 자동 오류 처리 기능 향상
* 사용자 지원 역할 업데이트 – 이제 로그인한 사용자의 프로세스를 종료할 수 있습니다
* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다




== VDS 6.0 릴리스: 2021년 5월 13일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 5월 13일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 추가 AVD 호스트 풀 속성 소개
* 백 엔드 서비스 문제가 발생할 경우 Azure 구현에서 추가 자동화 복원력을 제공합니다
* 서버에 연결 기능을 사용할 때 새 브라우저 탭에 서버 이름을 포함합니다
* 각 그룹의 사용자 수를 표시합니다
* 모든 구축 환경에서 서버에 연결 기능에 대한 복원력 향상
* 조직 및 최종 사용자를 위한 MFA 옵션 설정을 위한 추가 개선 사항
+
** SMS가 유일한 MFA 옵션으로 설정되어 있는 경우, 이메일 주소가 아닌 전화 번호가 필요합니다
** 이메일이 유일한 MFA 옵션으로 설정된 경우 이메일 주소는 필요하지만 전화번호는 필요하지 않습니다
** SMS와 이메일을 모두 MFA 옵션으로 설정한 경우 이메일 주소와 전화 번호가 모두 필요합니다


* 선명도 향상 - Azure가 스냅샷의 크기를 반환하지 않으므로 Azure 백업 스냅샷의 크기를 제거합니다
* Azure가 아닌 환경에서 스냅샷을 삭제하는 기능을 추가합니다
* 특수 문자를 사용할 때 AVD 호스트 풀 생성에 대한 버그 수정
* 리소스 탭을 통해 호스트 풀의 워크로드 스케줄링에 대한 버그 수정
* 대량 사용자 가져오기를 취소할 때 나타나는 오류 메시지에 대한 버그 수정
* 프로비저닝 컬렉션에 추가된 애플리케이션의 설정에 대한 가능한 시나리오에 대한 버그 수정
* 알림/메시지를 보내는 이메일 주소로 업데이트 – 이제 메시지는 noreply@vds.netapp.com 에서 전송됩니다
+
** 인바운드 이메일 주소를 안전하게 수신하는 고객은 이 이메일 주소를 추가해야 합니다






== VDS 6.0 릴리스: 2021년 4월 29일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 4월 29일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 개인 AVD 호스트 풀에 대한 Connect 시작 기능을 소개합니다
* Workspace 모듈에 스토리지 컨텍스트를 소개합니다
* Cloud Insights 통합을 통한 스토리지(Azure NetApp Files) 모니터링 도입
+
** IOPS 모니터링
** 지연 시간 모니터링
** 용량 모니터링


* VM 클론 생성 작업에 대한 로깅 향상
* 특정 워크로드 스케줄링 시나리오에 대한 버그 수정
* 특정 시나리오에서 VM의 시간대를 표시하지 않는 버그 수정
* 특정 시나리오에서 AVD 사용자를 로그아웃하지 않기 위한 버그 수정
* NetApp 브랜드 적용을 반영하는 자동으로 생성된 이메일 업데이트




== VDS 6.0 핫픽스: 2021년 4월 16일 금요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 4월 16일 금요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* 자동화된 인증서 관리를 개선한 지난밤의 업데이트 이후 발생한 자동 인증서 생성 문제를 해결합니다




== VDS 6.0 릴리스: 2021년 4월 15일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 4월 15일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* Cloud Insights 통합의 향상된 기능:
+
** 건너뛴 프레임 – 네트워크 리소스가 부족합니다
** 건너뛴 프레임 - 클라이언트 리소스가 부족합니다
** 프레임 건너뜀 – 서버 리소스 부족
** OS 디스크 - 읽기 바이트
** OS 디스크 - 쓰기 바이트
** OS 디스크 - 초당 읽기 바이트
** OS 디스크 - 초당 쓰기 바이트 수입니다


* 배포 모듈의 작업 기록에 대한 업데이트 - 작업 기록 처리 개선
* 일부 시나리오에서 디스크에서 Azure 백업을 CWMGR1로 복원할 수 없는 문제에 대한 버그 수정
* 인증서가 자동으로 업데이트 및 생성되지 않는 문제에 대한 버그 수정
* 중지된 배포가 빠르게 시작되지 않는 문제에 대한 버그 수정
* 작업 영역을 만들 때 상태 드롭다운 목록으로 업데이트합니다. 목록에서 "국가" 항목을 제거합니다
* NetApp 브랜드가 반영되는 추가 업데이트




== VDS 6.0 핫픽스: 2021년 4월 7일 수요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 4월 7일 수요일 오후 10시 – 오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* Azure에서 응답 시간이 점점 다양해지고 있기 때문에 구축 마법사 중에 Azure 자격 증명을 입력할 때 응답을 기다리는 시간이 늘어나고 있습니다.




== VDS 6.0 릴리스: 2021년 4월 1일 목요일

_ 구성 요소: _ 6.0 가상 데스크톱 서비스 _ 시기: _ 2021년 4월 1일 목요일 오후 10시~오후 11시 Eastern_Impact: _ 최종 사용자를 위한 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다. 가상 데스크톱 서비스에 대한 액세스는 계속 사용할 수 있습니다.



=== 가상 데스크톱 서비스

* NetApp Cloud Insights 통합 업데이트 - 새로운 스트리밍 데이터 포인트:
+
** NVIDIA GPU 성능 데이터
** 왕복 시간
** 사용자 입력 지연


* VM이 최종 사용자의 연결을 허용하지 않도록 설정된 경우에도 VM에 대한 관리 연결을 허용하도록 서버에 연결 기능을 업데이트합니다
* 후속 릴리즈에서 API가 향상되어 브랜딩 및 브랜딩이 활성화됩니다
* HTML5를 통해 서버에 연결 또는 RDS 사용자 세션을 통해 HTML5 연결에서 사용할 수 있는 작업 메뉴에 대한 향상된 가시성을 제공합니다
* 스크립트된 이벤트 활동 이름으로 지원되는 QTY 문자를 늘립니다
* 유형별로 프로비저닝 컬렉션 OS 선택 항목이 업데이트되었습니다
+
** AVD 및 Windows 10의 경우 VDI 컬렉션 유형을 사용하여 Windows 10 OS가 있는지 확인합니다
** Windows Server OS의 경우 공유 컬렉션 유형을 사용합니다


* 사전 예방을 위한 보안 및 성능 개선 사항을 제공합니다

