---
sidebar: sidebar 
permalink: Troubleshooting.printing_issues.html 
summary: 인쇄 문제 해결을 위한 단계별 가이드 
keywords:  
---
= 인쇄 문제 해결




== 오류

클라우드 데스크탑에서 로컬 프린터로 인쇄가 작동하지 않습니다.



== ThinPrint를 사용한 원격 데스크탑 서비스

VDS는 선택적으로 RDS(원격 데스크톱 서비스) 배포용 ThinPrint를 포함합니다. 소프트웨어 및 라이센스는 초기 배포 시 자동으로 구성됩니다. ThinPrint를 사용 중인 경우 다음 섹션을 통해 인쇄 관련 문제를 해결할 수 있습니다.



=== 원인

클라우드 데스크톱에 연결하는 방법은 다양합니다. 이러한 방법은 인쇄 기능을 수행하는 방법과 사용 중인 액세스 유형을 확인하는 방법에 따라 다릅니다.

. Windows 장치에서 CloudJumper의 액세스 클라이언트 사용
+
.. ThinPrint는 로컬 장치에서 실행되며 프린터와 클라우드 데스크탑 간의 통신을 중계합니다


. 모든 장치에서 HTML5 브라우저 사용
+
.. 브라우저는 인쇄 문서를 PDF로 출력하여 로컬에 다운로드하고 인쇄합니다


. 수동으로 구성된 RDP 클라이언트(일반적으로)를 Mac 또는 Linux 시스템에서 사용합니다
+
.. 로컬 프린터는 RDP 클라이언트에서 수동으로 "로컬 리소스"를 구성하여 클라우드 데스크톱과 공유됩니다.






=== 해상도

. 로컬 장치에서 문서를 인쇄하여 로컬 장치가 프린터에 성공적으로 연결되어 있는지 확인합니다.
. Windows 장치에서 Access Client를 사용하는 경우 ThinPrint를 제거하고 다시 설치합니다. https://www.thinprint.com/en/resources-support/software/clientsandtools/[]
. CloudJumper Support의 새로운 사례에서 액세스 유형과 첫 두 단계의 결과를 기록하십시오.




== Azure 가상 데스크톱

VDS는 AVD 환경에 대한 인쇄 솔루션 또는 고유 인쇄 구성을 구현하지 않습니다. 인쇄 질문은 Microsoft 또는 인쇄 기술 공급업체(구현된 경우)로 안내해야 합니다.
