---
sidebar: sidebar 
permalink: Management.Applications.application_entitlement_workflow.html 
summary: VDS의 최종 사용자에게 응용 프로그램을 배포하는 단계별 가이드 
keywords:  
---
= RDS용 애플리케이션 자격 워크플로우
:allow-uri-read: 




== 개요

VDS에는 강력한 응용 프로그램 자동화 및 사용 권한 기능이 내장되어 있습니다. 이 기능을 통해 사용자는 동일한 세션 호스트에 연결하는 동안 다른 애플리케이션에 액세스할 수 있습니다. 이 작업은 일부 사용자 지정 GPO에서 단축키를 숨기고 사용자 데스크톱에 선택적으로 바로 가기를 배치하는 자동화와 함께 수행됩니다.


NOTE: 이 워크플로는 RDS 배포에만 적용됩니다. AVD 응용 프로그램 자격 설명서는 를 참조하십시오 link:Management.Applications.AVD_application_entitlement_workflow.html["AVD에 대한 애플리케이션 사용 권한 워크플로"]

응용 프로그램은 직접 사용자에게 할당하거나 VDS에서 관리되는 보안 그룹을 통해 할당할 수 있습니다.

.애플리케이션 프로비저닝 프로세스는 높은 수준에서 다음 단계를 따릅니다.
. App Catalog에 앱을 추가합니다
. 작업 영역에 앱을 추가합니다
. 모든 세션 호스트에 애플리케이션을 설치합니다
. 바로 가기 경로를 선택합니다
. 사용자 및/또는 그룹에 앱을 할당합니다



NOTE: 3 및 4단계는 아래 그림과 같이 스크립트된 이벤트를 사용하여 완전히 자동화할 수 있습니다

.비디오 연습
video::19NpO8v15BE[youtube, ]


== 응용 프로그램을 App Catalog에 추가합니다

VDS Application Entitlement는 App Catalog(앱 카탈로그)로 시작합니다. 이 목록은 최종 사용자 환경에 배포할 수 있는 모든 응용 프로그램 목록입니다.

.카탈로그에 응용 프로그램을 추가하려면 다음 단계를 수행하십시오
. 에서 VDS에 로그인합니다 https://manage.cloudworkspace.com[] 기본 관리자 자격 증명을 사용합니다.
. 오른쪽 상단에서 사용자 이름 옆에 있는 화살표 아이콘을 클릭하고 설정 을 선택합니다.
. 앱 카탈로그 탭을 클릭합니다.
. 애플리케이션 카탈로그 제목 표시줄에서 앱 추가 옵션을 클릭합니다.
. 응용 프로그램 그룹을 추가하려면 응용 프로그램 가져오기 옵션을 선택합니다.
+
.. 응용 프로그램 목록에 맞는 형식을 만드는 Excel 서식 파일을 제공하는 대화 상자가 나타납니다.
.. 이 평가의 경우 NetApp VDS에서 가져오기를 위한 샘플 응용 프로그램 목록을 만들었습니다. 이 목록은 여기 에서 찾을 수 있습니다.
.. 업로드 영역을 클릭하고 응용 프로그램 템플릿 파일을 선택한 다음 가져오기 단추를 클릭합니다.


. 개별 애플리케이션을 추가하려면 앱 추가 버튼을 선택하면 대화 상자가 나타납니다.
+
.. 응용 프로그램의 이름을 입력합니다.
.. 외부 ID를 사용하여 제품 SKU 또는 청구 추적 코드(선택 사항)와 같은 내부 추적 식별자를 입력할 수 있습니다.
.. 응용 프로그램에 구독 제품으로 보고하려면 구독 상자를 선택합니다(선택 사항).
.. 제품이 버전(예: Chrome)별로 설치되지 않는 경우 버전 필요 없음 확인란을 선택합니다. 이를 통해 "지속적인 업데이트" 제품을 해당 버전을 추적하지 않고 설치할 수 있습니다.
.. 반대로, 제품이 여러 개의 명명된 버전(예: Quickbooks)을 지원하는 경우, 여러 버전을 설치할 수 있고 최종 사용자에게 권한을 부여할 수 있는 응용 프로그램 목록에서 사용 가능한 VDS 특정 버전을 가질 수 있도록 이 확인란을 선택해야 합니다.
.. VDS가 이 제품에 대해 바탕 화면 아이콘을 제공하지 않도록 하려면 “No User Desktop(사용자 바탕 화면 없음) 아이콘”을 선택합니다. 이 기능은 최종 사용자가 액세스할 수 있는 애플리케이션이 없으므로 SQL Server와 같은 "백엔드" 제품에 사용됩니다.
.. "앱이 연결되어 있어야 함"은 연결된 앱을 설치해야 하는 필요성을 적용합니다. 예를 들어, 클라이언트 서버 응용 프로그램에 SQL Server 또는 MySQL도 설치해야 할 수 있습니다.
.. 라이센스 필요 상자를 선택하면 VDS가 응용 프로그램 상태를 활성으로 설정하기 전에 이 응용 프로그램 설치를 위해 라이센스 파일을 업로드하도록 요청해야 함을 나타냅니다. 이 단계는 VDS의 응용 프로그램 세부 정보 페이지에서 수행됩니다.
.. 모두에게 표시 – 애플리케이션 권한은 다중 채널 계층 구조의 특정 하위 파트너로 제한될 수 있습니다. 평가를 위해 모든 사용자가 사용 가능한 응용 프로그램 목록에서 볼 수 있도록 확인란을 클릭합니다.






== Workspace에 응용 프로그램을 추가합니다

배포 프로세스를 시작하려면 앱을 작업 영역에 추가합니다.

.이렇게 하려면 다음 단계를 수행하십시오
. 작업 영역을 클릭합니다
. 앱 으로 스크롤합니다
. 추가 를 클릭합니다
. 응용 프로그램 확인란을 선택하고 필수 정보를 입력한 다음 응용 프로그램 추가를 클릭하고 응용 프로그램 추가를 클릭합니다.




== 응용 프로그램을 수동으로 설치합니다

애플리케이션이 Workspace에 추가되면 모든 세션 호스트에 해당 애플리케이션을 설치해야 합니다. 이 작업은 수동으로 수행하거나 자동화할 수 있습니다.

.세션 호스트에 애플리케이션을 수동으로 설치하려면 다음 단계를 수행하십시오
. 서비스 보드로 이동합니다.
. 서비스 보드 작업을 클릭합니다.
. 로컬 관리자로 연결할 서버 이름을 클릭합니다.
. 앱을 설치하고 시작 메뉴 경로에 이 앱의 바로 가기가 있는지 확인합니다.
+
.. Server 2016 및 Windows 10:C:\ProgramData\Microsoft\Windows\Start Menu\Programs의 경우


. 서비스 보드 작업으로 돌아가서 찾아보기 를 클릭하고 바로 가기 또는 바로 가기가 포함된 폴더를 선택합니다.
. 어떤 것을 선택하든 앱이 할당되면 최종 사용자 데스크톱에 표시됩니다.
. 폴더는 앱이 실제로 여러 응용 프로그램일 때 유용합니다. 예를 들어, "Microsoft Office"는 각 응용 프로그램을 폴더 안에 바로 가기로 사용하여 폴더로 배포하는 것이 더 쉽습니다.
. 설치 완료 를 클릭합니다.
. 필요한 경우, 생성된 아이콘 서비스 보드 작업 추가 를 열고 아이콘이 추가되었는지 확인합니다.




== 사용자에게 응용 프로그램을 할당합니다

응용 프로그램 사용 권한은 VDS에서 처리되며 응용 프로그램은 세 가지 방법으로 사용자에게 할당할 수 있습니다

.사용자에게 응용 프로그램을 할당합니다
. 사용자 세부 정보 페이지로 이동합니다.
. 응용 프로그램 섹션으로 이동합니다.
. 이 사용자에게 필요한 모든 응용 프로그램 옆에 있는 확인란을 선택합니다.


.응용 프로그램에 사용자를 할당합니다
. 작업 영역 세부 정보 페이지의 응용 프로그램 섹션으로 이동합니다.
. 응용 프로그램의 이름을 클릭합니다.
. 응용 프로그램을 사용하는 사용자 옆에 있는 확인란을 선택합니다.


.사용자 그룹에 응용 프로그램 및 사용자를 할당합니다
. 사용자 및 그룹 세부 정보로 이동합니다.
. 새 그룹을 추가하거나 기존 그룹을 편집합니다.
. 사용자 및 응용 프로그램을 그룹에 할당합니다.

