---
sidebar: sidebar 
permalink: Architectual.migrate_data_into_vds.html 
summary: 데이터 마이그레이션 시의 고려 사항 요약 
keywords:  
---
= 데이터 마이그레이션 고려 사항




== 개요

모든 유형의 클라우드 솔루션으로 마이그레이션하는 경우 범용 요구사항에 가까운 데이터 마이그레이션이 필요합니다. 관리자는 데이터를 가상 데스크톱으로 마이그레이션하는 작업을 담당하지만, NetApp의 경험을 활용하여 수많은 고객 마이그레이션에 큰 가치를 입증했습니다. 가상 데스크톱 환경은 단순히 호스팅된 Windows 환경이므로 원하는 모든 방법을 수용할 수 있습니다.

.일반적으로 마이그레이션되는 데이터:
* 사용자 프로필(데스크톱, 문서, 즐겨찾기 등...)
* 파일 서버 공유
* 데이터 공유(애플리케이션 데이터, 데이터베이스, 백업 캐시)


.가상 데스크톱 환경에는 데이터를 저장하고 구성하는 두 가지 기본 위치가 있습니다.
* User(일반적으로 H:\) 드라이브: 각 사용자에 대해 볼 수 있는 매핑된 드라이브입니다.
+
** 이 경로는 <drive>:\home\CustomerCode\user.name\path 에 다시 매핑됩니다
** 각 사용자는 자신의 H:\ 드라이브를 가지고 있으며 다른 사용자를 볼 수 없습니다


* 공유(일반적으로 I:\) 드라이브: 모든 사용자가 볼 수 있는 공유 매핑된 드라이브입니다
+
** 드라이브>:\data\CustomerCode\path에 다시 매핑됩니다
** 모든 사용자가 이 드라이브에 액세스할 수 있습니다. 포함된 폴더/파일에 대한 액세스 수준은 VDS의 폴더 섹션에서 관리됩니다.






== 일반 마이그레이션 프로세스

. 데이터를 클라우드 환경으로 복제합니다
. H:\ 및 I:\드라이브에 대한 적절한 경로로 데이터를 이동합니다
. 가상 데스크톱 환경에서 적절한 사용 권한을 할당합니다




== FTPS 전송 및 고려 사항



=== FTPS를 이용한 마이그레이션

. CWA 배포 프로세스 중에 FTPS 서버 역할이 활성화된 경우 VDS에 로그인하고 보고서로 이동한 다음 조직의 마스터 클라이언트 보고서를 실행하여 FTPS 자격 증명을 수집합니다
. 데이터를 업로드합니다
. H:\ 및 I:\ 드라이브에 대한 적절한 경로로 데이터를 이동합니다
. 폴더 모듈을 통해 가상 데스크톱 환경에 적절한 권한을 할당합니다



NOTE: FTPS를 통해 데이터를 전송할 때 중단이 발생할 경우 데이터가 의도한 대로 전송되지 않습니다. Virtual Desktop Services에서 관리하는 서버가 야간에 재부팅되기 때문에 표준 야간 전송 전략이 중단될 수 있습니다. 이를 위해 관리자는 마이그레이션 모드를 활성화하여 VM이 1주일 동안 재부팅되지 않도록 할 수 있습니다.

마이그레이션 모드 활성화는 쉽습니다. 조직으로 이동한 다음 Virtual Desktop Settings(가상 데스크톱 설정) 섹션으로 스크롤하여 Migration Mode(마이그레이션 모드) 확인란을 선택한 다음 Update(업데이트) 를 클릭합니다.


NOTE: NetApp은 조직의 게이트웨이 강화를 통해 PCI, HIPAA 및 NIST 제어를 충족하는 규정 준수 설정을 사용할 것을 권장합니다. 이렇게 하면 포트 21을 통한 암호화되지 않은 기본 전송을 수락하지 않는 경우 기본 FTP 서버 역할을 사용할 수 없습니다. FileZilla는 SFTP를 허용하지 않으므로 FTPS를 사용하여 포트 990을 통해 연결해야 합니다.

이 설정을 활성화하려면 CWMGR1에 연결하고 CwVmAutomationService 프로그램으로 이동한 다음 PCI v3 준수를 활성화하십시오.



== 동기화 도구 및 고려 사항

EFSS 또는 동기화 도구라고도 하는 Enterprise File Sync and Share는 컷오버가 완료될 때까지 각 측의 변경 사항을 캡처하므로 데이터 마이그레이션에 매우 유용합니다. Office 365와 함께 제공되는 OneDrive와 같은 도구를 사용하면 파일 서버 데이터를 동기화할 수 있습니다. 또한 공유 데이터를 공유에 한 번 배포할 수 있을 때 사용자가 공유 콘텐츠를 VDI 서버에 동기화하지 않는 한 사용자와 VM 사이에 1:1 관계가 있는 VDI 사용자 배포에도 유용합니다(일반적으로 I:\). 전체 조직이 사용할 수 있도록 추진합니다. SQL 및 유사 데이터 마이그레이션(열린 파일)

.일반적인 동기화 및/또는 마이그레이션 솔루션은 다음과 같은 파일 형식을 포함하는 열린 파일을 전송하지 않습니다.
* 사서함(.ost) 파일
* QuickBooks 파일
* Microsoft Access 파일
* SQL 데이터베이스


즉, 전체 파일의 단일 요소(예: 새 전자 메일 1개가 나타남) 또는 데이터베이스(앱의 시스템에 새 레코드 1개가 입력됨)가 있을 경우 전체 파일이 다르고 표준 동기화 도구(예: Dropbox)가 됩니다. 완전히 새로운 파일이라고 생각하고 다시 이동해야 합니다. 필요한 경우 타사 공급자로부터 구입할 수 있는 특수 도구가 있습니다.

이러한 마이그레이션을 처리하는 또 다른 일반적인 방법은 데이터베이스 가져오기/내보내기 작업을 간소화해 온 타사 VAR에 대한 액세스를 제공하는 것입니다.



== 드라이브를 배송하십시오

많은 데이터 센터 공급업체는 더 이상 하드 드라이브를 제공하지 않습니다. 즉, 특정 정책 및 절차를 따라야 합니다.

Microsoft Azure를 사용하면 조직에서 Azure Data Box를 사용할 수 있습니다. 관리자는 Microsoft 담당자와 조정하여 이 상자를 활용할 수 있습니다.
