= 개요
:allow-uri-read: 




== 개요

이 문서에서는 AVD 최종 사용자 액세스를 유지하면서 VDS 및 NetApp 제어 제거를 다룹니다. 앞으로는 기본 Azure/Windows 관리 툴을 사용할 것입니다. 이 프로세스가 완료되면 support@spotpc.netapp.com 으로 연락하여 NetApp이 백 엔드 및 청구 시스템을 정리할 수 있도록 하는 것이 좋습니다.



== 초기 상태입니다

* Avd 배포
* TDS1은 FS Logix 파일 공유 소프트웨어입니다
* TS1은 세션 호스트입니다
* 사용자가 로그인했으며 FS Logix 디스크가 다음 사이트에 생성되었습니다.
+
 \\****TSD1\****-Pro$\ProfileContainers (**** = Unique Company Code)




== CW Agent 서비스를 삭제합니다

CW 에이전트는 환경의 모든 컴퓨터에서 실행됩니다. 이 프로세스를 시작하는 서비스는 환경의 모든 VM에서 다음 명령으로 제거해야 합니다. CWMGR1은 대부분의 경우 VM이 종료되고 결국 삭제되므로 건너뛸 수 있습니다. 이 작업은 스크립트 기반 자동화를 통해 실행하는 것이 이상적입니다. 아래 비디오에서는 수동으로 수행했음을 보여 줍니다.

 C:\Program files\CloudWorkspace\CwAgent\CwAgent.exe -u


=== CW Agent 서비스 비디오를 삭제합니다

video::l9ASmM5aap0[youtube]


== CW 에이전트 디렉터리를 삭제합니다

이전 설치 제거 시 CW Agent를 실행하는 서비스가 제거되었지만 파일은 그대로 남아 있습니다. 디렉토리를 삭제합니다.

 "C:\Program Files\CloudWorkspace"


=== CW Agent 디렉토리 비디오를 삭제합니다

video::hMM_z4K2-iI[youtube]


== 시작 바로 가기를 제거합니다

시작 항목 디렉토리에는 이전 단계에서 삭제된 파일에 대한 두 개의 바로 가기가 들어 있습니다. 최종 사용자 오류 메시지를 방지하려면 이러한 파일을 삭제해야 합니다.

....
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\Pen.lnk"
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\CwRemoteApps.lnk"
....


=== 시작 바로 가기 비디오를 제거합니다

video::U0YLZ3Qfu9w[youtube]


== '사용자' 및 '회사' GPO의 연결을 해제합니다

VDS에 의해 구현되는 GPO는 세 가지가 있습니다. 두 개의 연결을 해제하고 세 번째 콘텐츠의 내용을 검토하는 것이 좋습니다.

연결 해제:

* ADDC 사용자 > 클라우드 작업 공간 회사
* ADDC 사용자 > 클라우드 작업 영역 사용자


검토:

* AADDC 컴퓨터 > 클라우드 작업 영역 컴퓨터




=== '사용자' 및 '회사' GPO 비디오의 연결을 해제합니다

video::cb68ri3HKUw[youtube]


== CWMGR1을 종료합니다

GPO 변경 사항을 적용하면 CWMGR1 VM을 종료할 수 있습니다. AVD 기능이 계속 확인되면 이 VM을 영구적으로 삭제할 수 있습니다.

다른 서버 역할이 실행 중인 경우(예 DC, FTP 서버…). 이 경우 CWMGR1에서 VDS 기능을 비활성화하기 위해 세 가지 서비스를 비활성화할 수 있습니다.

* CW 에이전트(위 참조)
* CW 자동화 서비스
* CW VM 자동화




=== CWMGR1 비디오를 종료합니다

video::avk9HyIiC_s[youtube]


== NetApp VDS 서비스 계정을 삭제합니다

VDS에서 사용하는 Azure AD 서비스 계정을 제거할 수 있습니다. Azure Management Portal에 로그인하고 사용자를 삭제합니다.

* CloudWorkspaceSVC
* CloudWorkspaceCASVC


다른 사용자 계정을 유지할 수 있습니다.

* 최종 사용자
* Azure 관리자
* .tech 도메인 관리자




=== NetApp VDS 서비스 계정 비디오를 삭제합니다

video::_VToVNp49cg[youtube]


== 앱 등록을 삭제합니다

VDS를 배포할 때 두 개의 앱 등록이 이루어집니다. 삭제할 수 있는 항목은 다음과 같습니다.

* Cloud Workspace API를 참조하십시오
* 클라우드 작업 공간 AVD




=== 앱 등록 동영상을 삭제합니다

video::iARz2nw1Oks[youtube]


== 엔터프라이즈 응용 프로그램을 삭제합니다

VDS 배포 시 두 개의 엔터프라이즈 응용 프로그램이 배포됩니다. 삭제할 수 있는 항목은 다음과 같습니다.

* 클라우드 작업 공간
* Cloud Workspace Management API를 참조하십시오




=== 엔터프라이즈 응용 프로그램 비디오를 삭제합니다

video::3eQzTPdilWk[youtube]


== CWMGR1이 중지되었는지 확인합니다

최종 사용자가 여전히 연결할 수 있는지 테스트하기 전에 실제 테스트를 위해 CWMGR1이 중지되었는지 확인합니다.



=== CWMGR1이 정지 비디오인지 확인합니다

video::Ux9nkDk5lU4[youtube]


== 로그인 및 최종 사용자

성공을 확인하려면 최종 사용자로 로그인하고 기능이 유지되는지 확인합니다.



=== 로그인 및 최종 사용자 비디오

video::SuS-OTHJz7Y[youtube]