= 개요




== 개요

VDS는 개념을 논리적 계층의 다양한 계층으로 구성합니다. 이 문서에서는 이 두 구성 방법이 어떻게 서로 잘 맞는지 간략하게 설명합니다.



=== VDS 조직 구조

VDS 관리 포털은 에서 찾을 수 있습니다 https://manage.vds.netapp.com[]. 이 웹 인터페이스는 모든 VDS 관련 개체를 관리하기 위한 단일 창입니다. VDS 웹 UI에는 다음과 같은 구성 요소 및 논리적 컨테이너 계층이 있습니다.



==== VDS 배포

Deployment_는 _VDS 작업 공간 _ 을(를) 구성하고 포함하는 VDS 개념입니다. 특정 배포 아키텍처에서 배포에는 여러 VDS 작업 영역이 포함될 수 있습니다.


NOTE: 단일 배포 내에서 다중 VDS 작업 공간을 실행하는 것은 "멀티 테넌시"라고 하며 RDS 구축 시 유일한 옵션이며 AVD 배포에서는 이 방법을 지원하지 않습니다.

배포는 Active Directory 도메인에 의해 정의되며 AD 도메인과 배포 사이에는 1:1 관계가 있습니다.

배포의 모든 VDS 작업 영역 간에 공유되는 배포를 지원하기 위해 배포된 특정 VM 리소스가 있습니다. 예를 들어 모든 배포에는 VDS 응용 프로그램, SQL Express 데이터베이스를 실행하는 서버인 "CWMGR1"이라는 VM이 포함되어 있으며 배포 내에서 VDS 작업 공간(및 포함된 리소스)을 쉽게 관리할 수 있습니다.



==== VDS 작업 공간


WARNING: " * VDS * Workspace"와 " * AVD * Workspace"는 차이가 있습니다.

VDS Workspace는 클라이언트(최종 사용자) 리소스의 배포 내에 있는 논리적 컨테이너입니다. 이러한 리소스에는 가상 머신(세션 호스트, 애플리케이션 서버, 데이터베이스 서버, 파일 서버 등), 가상 네트워킹, 스토리지 및 기타 하이퍼바이저 인프라스트럭처

VDS 작업 공간에는 사용자, 보안 그룹, 워크로드 스케줄링, 응용 프로그램, 자동화, VM 및 AVD 구성.

일반적으로 VDS Workspace는 단일 회사 또는 (엔터프라이즈 배포 시) 비즈니스 단위에 맞게 조정됩니다.



==== VDS 사이트

배포 내에서 여러 사이트를 만들어 여러 인프라 공급자를 나타낼 수 있으며, 모두 단일 배포 내에서 관리됩니다.

이 기능은 단일 회사 또는 부서에서 여러 물리적 위치(예: 북미 및 EMEA), 하이퍼바이저 가입(사업부에 비용 조정) 및 하이퍼바이저(예: Azure, Google Compute 및 vSphere의 사내 HCI 사용자)에 사용자와 앱을 호스팅해야 하는 경우에 유용합니다.



==== Avd 작업 영역


WARNING: " * VDS * Workspace"와 " * AVD * Workspace"는 차이가 있습니다.

AVD 작업 영역은 VDS 작업 영역 및 VDS 사이트 내에 있는 논리 컨테이너입니다. 동일한 배포에서 관리 및 운영 정책을 분할하기 위해 VDS 사이트와 유사하게 사용할 수 있습니다.



==== Avd 호스트 풀

Avd 호스트 풀은 AVD 작업 공간 내에 있는 논리 컨테이너이며, 세션 호스트 및 앱 그룹 사용자를 보류하여 사용자 세션을 서버에 설정하고 개별 리소스에 대한 액세스를 제어합니다.



==== Avd 앱 그룹

각 AVD 호스트 풀은 단일 "데스크톱" 애플리케이션 그룹으로 시작됩니다. 사용자 및/또는 그룹을 이(또는 다른) 앱 그룹에 할당하여 할당된 사용자에게 앱 그룹의 리소스에 대한 액세스를 허용할 수 있습니다.

VDS의 호스트 풀 내에서 추가 앱 그룹을 생성할 수 있습니다. 모든 추가 앱 그룹은 전체 Windows 데스크톱 환경이 아닌 "RemoteApp" 앱 그룹이며 RemoteApp 리소스를 제공합니다.
