= 개요




== 개요

NetApp VDS(가상 데스크톱 서비스)에는 추가 비용 없이 SMS/이메일 기반 MFA 서비스가 포함됩니다. 이 서비스는 다른 서비스(예 Azure Conditional Access)를 사용하여 VDS에 대한 관리자 로그인과 가상 데스크톱에 대한 사용자 로그인을 보호할 수 있습니다.



== MFA 기본 사항

* VDS MFA는 admin 사용자, 개별 최종 사용자에게 할당하거나 모든 최종 사용자에게 적용할 수 있습니다
* VDS MFA는 SMS 또는 이메일 알림을 보낼 수 있습니다
* VDS MFA는 셀프 서비스 초기 설정 및 재설정 기능을 제공합니다




== 가이드 범위

이 가이드에서는 최종 사용자 환경 그림과 함께 MFA 설정을 안내합니다

.본 가이드에서는 다음 주제를 다룹니다.
. <<Enabling MFA for Individual Users,개별 사용자를 위한 MFA 활성화>>
. <<Requiring MFA for All Users,모든 사용자에 대해 MFA 필요>>
. <<Enabling MFA for Individual Administrators ,개별 관리자를 위한 MFA 활성화>>
. <<End User Initial Setup,최종 사용자 초기 설정>>




== 개별 사용자를 위한 MFA 활성화

MFA는 사용자 세부 정보 페이지의 개별 사용자에 대해 _다단계 인증 사용_을 클릭하여 활성화할 수 있습니다

작업 공간 > 작업 공간 이름 > 사용자 및 그룹 > 사용자 이름 > 다중 요소 인증 사용 > 업데이트 를 선택합니다

또한 MFA는 모든 사용자에게 할당될 수 있습니다. 이 설정이 있는 경우 확인란이 선택되며 _ (클라이언트 설정을 통해) _ 이(가) 확인란 레이블에 추가됩니다.



== 모든 사용자에게 MFA 필요

MFA는 모든 사용자에 대해 _MFA 를 클릭하여 작업 영역 세부 정보 페이지의 모든 사용자에게 설정 및 적용할 수 있습니다

작업 영역 > 작업 영역 이름 > 모든 사용자에 대한 MFA 설정 > 업데이트 를 클릭합니다



== 개별 관리자를 위한 MFA 활성화

MFA는 VDS 포털에 액세스하는 관리자 계정에서도 사용할 수 있습니다. 이 기능은 관리자 세부 정보 페이지에서 관리자별로 활성화할 수 있습니다. 관리자 > 관리자 이름 > 다중 요소 인증 필요 > 업데이트



== 초기 설정

MFA를 활성화한 후 처음 로그인하면 사용자 또는 관리자에게 이메일 주소 또는 휴대폰 번호를 입력하라는 메시지가 표시됩니다. 등록 성공 여부를 입력하고 확인할 수 있는 확인 코드를 받게 됩니다.
