= 개요



NOTE: CWS의 v5.0에 대한 추가 반복 릴리스가 없습니다. 모든 릴리스는 핫픽스로 간주됩니다.



== 개요

CloudJumper는 2016년 4분기부터 일반적인 구축을 위한 Cloud Workspace Suite 5.0을 출시했습니다. 이 릴리스에는 CWS API 및 관리 제어 인터페이스 업데이트가 모두 포함되어 있습니다. 이 릴리스는 중요한 변경 사항을 제공하며 버전 4.x 엔터티에 대해 "이전 버전과 호환"되지 않습니다.

버전 4.x는 모든 파트너 SDDC(소프트웨어 정의 데이터 센터)가 5.0 플랫폼으로 업그레이드될 때까지 계속 지원되며, CloudJumper는 각 파트너와 협력하여 업그레이드를 완료하고 기존 서비스를 중단하지 않습니다. 전환할 업그레이드 비용 또는 구축 비용은 없습니다. CWS 5는 이전 버전의 모든 기능을 계속 지원하고 관리자 및 최종 사용자 환경을 모두 향상시키는 새로운 기능을 확장하며 이전의 Cloud Workspace Suite 릴리스에 도입된 수상 경력에 빛나는 자동화 및 오케스트레이션을 더욱 향상시킵니다.

CloudJumper는 CWS 5.0을 통해 모든 플랫폼 API를 REST API 형식으로 다시 작성했으며 이전 SOAP API를 완전히 폐기했습니다. 이 업데이트된 아키텍처를 통해 CloudJumper의 기능이 더욱 쉽고 빨라졌으며, 외부 개발자가 Cloud Workspace를 기반으로 서비스와 제품을 확장할 수 있는 더욱 친숙한 환경을 구축할 수 있게 되었습니다.



== 하이라이트

* UI/UX Rewrite 완료
* Azure AD 통합
* Azure SDDC 셀프 서비스 구축
* 앱 서비스
* 리소스 스케줄링
* 라이브 서버 확장 – 크로스 플랫폼
* 자동화된 서버 클론 생성 – 크로스 플랫폼
* 클라이언트별로 드라이브 공유를 사용자 지정합니다




== 주요 기능



=== Azure Active Directory(AD) 통합

* SDDC를 프라이빗 클라우드 Active Directory로 구축하거나 Microsoft Azure-AD-as-a-Service를 사용하십시오
* CWS와 Office365를 결합합니다
* Azure 기반 SSO 및 MFA 지원




=== Azure SDDC 셀프 서비스 구축

* Azure와의 완벽한 통합
* 새로운 DC를 빠르게 구축합니다
* WAAS, App Services, Private Web App 및 SharePoint 등 Cloud Workspace 관리 워크로드를 포함한 모든 워크로드에 Azure 내에서 프라이빗 엔터프라이즈 클라우드를 배포합니다




=== 앱 서비스

* 응용 프로그램을 격리된 서비스 구성 요소로 게시하기 위해 응용 프로그램 사일로를 배포합니다
* '공용' 응용 프로그램 서버에서 다양한 사용자 지정 엔터티로 제공되는 응용 프로그램입니다
* 단일 애플리케이션 전용 서버 풀에 설치된 애플리케이션
* 앱은 사용자 프로필 및 데이터 계층 요구 사항에서 분리됩니다
* 확장성이 뛰어난 앱 서비스 구축
* 여러 앱 서비스를 사용자 컬렉션으로 결합할 수 있습니다
* CWS 라이선스 추적 및 사용 현황 보고




=== 라이브 서버 확장 – 크로스 플랫폼

* 서버 리소스/활성 서버의 지능형 자동 확장
* 사용자 로드가 변경되는 동안 동적 증가/감소를 통해 서버 리소스를 긴밀하게 관리합니다
* 작업 부하가 달라지므로 서버 리소스를 자동으로 확대/축소할 수 있습니다




=== 자동화된 서버 클론 생성 – 플랫폼 간

* 정의된 사용자 수가 증가할 때까지 자동으로 서버 수를 늘립니다
* 사용 가능한 리소스 풀에 추가 서버를 추가합니다
* CWS 라이브 서버 확장 기능과 결합하여 완전히 자동화된 솔루션을 만듭니다




=== 리소스 스케줄링

* 고객별로 서비스 시간을 예약합니다
* 퍼블릭 클라우드를 위한 비용 억제
* 사용하지 않을 때는 시스템을 종료하고 미리 정의된 일정에 따라 시스템을 다시 활성화합니다

