= 날짜: 2020년 7월 29일 목요일 오후 11시 동부
:allow-uri-read: 




== 날짜: 2020년 7월 29일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 Windows용 VDS 클라이언트 업데이트를 실행할 때 이를 볼 수 있습니다



=== 개선 사항

* 설치 프로세스 간소화 - 새로운 최종 사용자는 더 이상 Windows용 VDS 클라이언트를 설치할 때 약관에 동의할 필요가 없습니다
* 설치 프로세스 중에 확인을 추가하여 최종 사용자의 장치가 자동 업데이트가 발생한 위치에 액세스할 수 있는지 확인합니다




== 날짜: 2020년 5월 27일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 버그 수정

* 제공된 암호가 충분히 길지 않을 경우 표시되는 오류 메시지의 명확성이 향상되었습니다




== 날짜: 2020년 5월 13일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 최종 사용자의 리소스 가용성을 보장하는 추가 자동화




=== 업데이트

* 자동 업데이트에 액세스하는 데 필요한 URL이 변경됩니다. 인바운드 트래픽을 적극적으로 보호하지 않는 경우 변경할 필요가 없습니다.
+
** 변경 사항이 없더라도 모든 최종 사용자는 계속 데스크톱에 액세스할 수 있습니다
** 인바운드 트래픽을 적극적으로 보호하려는 조직은 자동 업데이트에 액세스할 수 있도록 최종 사용자 장치가 위의 새 URL에 액세스할 수 있도록 보장해야 합니다
** 현재 업데이트 소스는 다음과 같습니다.
+
*** 주: cwc.cloudworkspace.com
*** 보조: cloudjumper.com


** 새로운 업데이트 소스는 다음과 같습니다.
+
*** 기본: bin.vdsclient.app
*** 보조: cwc.cloudworkspace.com


** Windows용 Cloud Workspace Client를 설치하는 새 사용자는 나열된 URL에 계속 액세스할 수 있어야 합니다 link:https://docs.netapp.com/us-en/virtual-desktop-service/Reference.end_user_access.html#remote-desktop-services["여기"]






== 날짜: 2020년 4월 29일 목요일 오후 11시 동부

영향: 사용자가 다음에 RDP 클라이언트 업데이트를 시작할 때 RDP 클라이언트 업데이트를 보게 됩니다

(이 릴리스에 대한 업데이트 없음)



== 날짜: 2020년 4월 15일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 버그 수정

* 네트워크 테스트 결과가 의도한 대로 전송되지 않는 문제를 해결합니다




== 날짜: 2020년 4월 1일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* RemoteApp 응용 프로그램으로 업데이트 - 사용자가 개별 앱을 실행할 때 자격 증명을 묻는 메시지가 더 이상 표시되지 않습니다
* 최종 사용자가 인쇄를 위해 ThinPrint 및 Windows 프린터 리디렉션 사용 간을 전환할 수 있도록 업데이트합니다
* Windows Designer용 VDS 클라이언트가 인쇄 리디렉션 서비스를 제외할 수 있도록 업데이트합니다




== VDS 5.4 릴리스: 목요일, 2021년 1월 21일

_ 구성 요소: _ 5.4 가상 데스크톱 서비스 _ 시기: _ 2021년 1월 21일 목요일 오후 10시 - 오후 11시 Eastern_Impact: _ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이를 볼 수 있습니다



=== 개선 사항

* 최종 사용자 환경 개선 – 외부 도메인에서 가져온 사용자를 보다 효율적으로 처리합니다




== 날짜: 2020년 6월 11일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 설치할 수 있는 최신 AVD RDP 클라이언트를 업데이트합니다




== 날짜: 2020년 5월 28일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* NetApp 브랜드/구문 업데이트 참고 – 이 새로운 브랜딩은 다음에 적용됩니다.
+
** 새 VDS 클라이언트 다운로드
** Windows 설치용 기존, 편집되지 않은 VDS 클라이언트
** 기존 사용자 지정 편집/브랜드 클라이언트는 사용자 지정되지 않은 경우에만 새 배너 이미지를 받습니다. 배너 이미지가 사용자 정의된 경우 그대로 유지됩니다. 다른 모든 색과 구문은 동일하게 유지됩니다.






== 날짜: 2020년 5월 14일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2020년 4월 30일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 버그 수정

* 셀프 서비스 암호 재설정이 제공되지 않은 일부 시나리오에 대한 버그 수정




== 날짜: 2020년 4월 16일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2020년 4월 2일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2020년 3월 19일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2020년 3월 5일 목요일 오후 10시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* RDS 게이트웨이에서 기존 자격 증명 유형이 최신 패치와 혼합되어 세션 호스트에 연결할 수 없는 RDP 프로토콜을 사용하여 등고선 버그를 정상적으로 처리합니다
+
** 최종 사용자의 워크스테이션이 외부 관리자, 내부 고객 관리자 또는 워크스테이션의 기본 설정을 통해 레거시 자격 증명 유형을 사용하도록 설정되어 있는 경우, 이 릴리스 이전에 사용자에게 영향을 미칠 가능성이 매우 희박합니다


* Cloud Workspace Client Designer의 정보 단추를 업데이트된 문서 소스로 가리킵니다
* Cloud Workspace Client Designer의 자동 업데이트 프로세스가 개선되었습니다




== 날짜: 2020년 2월 20일 목요일 오후 10시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 보안, 안정성 및 확장성의 사전 개선




=== 고려 사항

* Windows용 Cloud Workspace Client는 사용자가 4/2 이전에 실행하는 한 계속해서 자동 업데이트를 수행합니다. 사용자가 4/2가 되기 전에 Windows용 Cloud Workspace Client를 실행하지 않는 경우에도 데스크톱에 대한 연결은 계속 작동하지만 자동 업데이트 기능을 다시 시작하려면 Windows용 Cloud Workspace Client를 제거하고 다시 설치해야 합니다.
* 조직에서 웹 필터링을 사용하는 경우 자동 업데이트 기능이 그대로 유지되도록 cwc.cloudworkspace.com 및 cwc-cloud.cloudworkspace.com 에 대한 허용 목록 액세스를 허용하십시오




== 날짜: 2020년 1월 9일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 12월 19일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 12월 2일 월요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 11월 14일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 사용자가 '귀하의 서비스가 현재 오프라인 상태입니다' 메시지를 보게 되는 이유에 대한 명확성이 향상되었습니다. 메시지가 나타날 수 있는 원인은 다음과 같습니다.
+
** 세션 호스트 서버가 오프라인 상태가 되도록 예약되었으며 사용자에게 요청 시 깨우기 권한이 없습니다.
+
*** 사용자가 Cloud Workspace Client를 사용 중인 경우 "현재 서비스가 오프라인 상태로 예약되었습니다. 액세스가 필요한 경우 관리자에게 문의하십시오."라는 메시지가 표시됩니다.
*** 사용자가 HTML5 로그인 포털을 사용 중인 경우 "현재 서비스가 오프라인 상태로 예약되어 있습니다. 액세스가 필요한 경우 관리자에게 문의하십시오.”


** 세션 호스트 서버가 온라인 상태가 되도록 예약되었으며 사용자에게 요청 시 깨우기 권한이 없습니다.
+
*** 사용자가 Cloud Workspace Client를 사용 중인 경우 "현재 서비스가 오프라인 상태입니다. 액세스 권한이 필요한 경우 관리자에게 문의하십시오."라는 메시지가 표시됩니다.
*** 사용자가 HTML5 로그인 포털을 사용 중인 경우 "현재 서비스가 오프라인 상태입니다. 액세스가 필요한 경우 관리자에게 문의하십시오.”


** 세션 호스트 서버가 오프라인 상태로 예약되고 사용자에게 요청 시 깨우기 권한이 있습니다.
+
*** 사용자가 Cloud Workspace Client를 사용 중인 경우 "현재 서비스가 오프라인 상태입니다. 액세스 권한이 필요한 경우 관리자에게 문의하십시오."라는 메시지가 표시됩니다.
*** 사용자가 HTML5 로그인 포털을 사용 중인 경우 "현재 서비스가 오프라인 상태로 예약되어 있습니다. 시작 을 클릭하여 온라인으로 연결하고 연결합니다.”


** 세션 호스트 서버가 온라인 상태가 되도록 예약되었으며 사용자에게 요청 시 깨우기 권한이 있습니다.
+
*** 사용자가 Cloud Workspace Client를 사용 중인 경우 "Workspace를 시작할 때까지 2-5분 정도 기다려 주십시오."라는 메시지가 표시됩니다.
*** 사용자가 HTML5 로그인 포털을 사용 중인 경우 "현재 서비스가 오프라인 상태입니다. 시작 을 클릭하여 온라인으로 연결하고 연결합니다.”








== 날짜: 2019년 10월 31일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 11월 17일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* AVD 요소 추가:




== 날짜: 2019년 10월 3일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 코드 서명 인증서의 처리 기능이 향상되었습니다


버그 수정

* 할당된 앱이 없는 RemoteApp에 액세스하는 사용자에게 오류가 발생하는 문제를 해결합니다
* 사용자가 가상 데스크톱에 로그인하는 도중에 인터넷 연결이 끊어지는 문제를 해결합니다




== 날짜: 2019년 9월 19일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* AVD 요소 추가:
+
** 최종 사용자가 AVD 리소스에 액세스할 수 있는 경우 AVD 탭을 표시합니다
** AVD 탭에는 다음과 같은 옵션이 제공됩니다.
+
*** AVD RD 클라이언트가 설치되어 있지 않은 경우 설치합니다
*** AVD RD 클라이언트가 설치된 경우 RD 클라이언트를 실행합니다
*** 웹 클라이언트를 실행하여 AVD HTML5 로그인 페이지로 이동합니다
*** 완료 를 클릭하여 이전 페이지로 돌아갑니다








== 날짜: 2019년 9월 5일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 8월 22일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 8월 8일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 7월 25일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 7월 11일 목요일 오후 11시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 6월 21일 금요일 오전 4시

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다

* 이 릴리스 주기는 업데이트되지 않습니다.




== 날짜: 2019년 6월 7일 금요일 오전 4시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* Cloud Workspace Client가 .rdp 파일에 대해 설정된 파일 형식 연결에 관계없이 RDP 연결을 자동으로 시작하도록 설정합니다




== 날짜: 2019년 5월 24일 금요일 오전 4시

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 로그인 프로세스 동안 성능이 향상되었습니다
* 출시 시 로드 시간 단축




== 날짜: 2019년 5월 10일 금요일 오전 4시

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 로그인 프로세스 동안 성능이 향상되었습니다
* 출시 시 로드 시간 단축




== 날짜: 2019년 4월 12일 금요일 오전 4시 동부

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* 필요할 때 깨우기를 위한 향상된 로그인 속도
* Windows용 Cloud Workspace Client를 성공적으로 시작한 후 사용자 인터페이스에서 공간을 확보하기 위해 피드백 버튼을 제거합니다


버그 수정

* 요청 시 깨우기 작업이 실패한 후 로그인 단추가 응답하지 않는 문제를 해결합니다




== 날짜: 2019년 3월 15일 금요일 오전 4시

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* Cloud Workspace Client for Windows를 사용하는 관리자가 지원 이메일 주소 또는 전화 번호를 제공할 수 있도록 허용합니다. 두 가지를 모두 사용할 필요가 없습니다
* Cloud Workspace Client에 제공된 HTML5 URL이 유효한 URL이 되도록 하십시오. 그렇지 않으면 기본적으로 https;//login.cloudjumper.com 가 됩니다
* 최종 사용자를 위한 업데이트 적용 프로세스 간소화




== 날짜: 2019년 2월 29일 금요일 오전 4시

_영향:_ 사용자는 다음에 RDP 클라이언트 업데이트를 시작할 때 이 업데이트를 보게 됩니다



=== 개선 사항

* AppData 폴더가 c:\users\<사용자 이름>\appdata\local\RDPClient에서 c:\users\<사용자 이름>\appdata\local\Cloud Workspace로 옮겨졌습니다
* 사용자가 여러 릴리즈에서 클라이언트를 업데이트하지 않은 경우 업그레이드 경로를 간소화하는 메커니즘을 구현했습니다
* 클라이언트의 베타 버전으로 작업하는 사용자에 대해 향상된 로그 세부 정보가 활성화되었습니다


버그 수정

* 업데이트 프로세스 중에는 더 이상 여러 줄이 표시되지 않습니다




== 날짜: 2019년 2월 15일 금요일 오전 4시

_영향:_ RDP 클라이언트 업데이트를 실행하면 사용자에게 표시됩니다



=== 개선 사항

* 원격 설치에 대해 자동/자동 설치 옵션을 활성화합니다
+
** 설치 플래그는 다음과 같습니다.
+
*** /s 또는 /silent 또는 /q 또는 /quiet
+
**** 이러한 플래그는 클라이언트를 백그라운드에서 자동으로 설치합니다. 설치가 완료되면 클라이언트가 시작되지 않습니다


*** /p 또는 /passive
+
**** 이 두 가지 모두 설치 프로세스를 표시하지만 입력이 필요하지 않으며 설치가 완료되면 클라이언트가 시작됩니다


*** /nothinprint 를 선택합니다
+
**** 설치 프로세스에서 ThinPrint를 제외합니다






* HKLM\Software\CloudJumper\Cloud Workspace Client\Branding에 레지스트리 항목이 추가되었습니다.
+
** ClipboardSharingEnabled: True/False – 클립보드 리디렉션을 허용 또는 해제합니다
** RemoteAppEnabled: True/False – RemoteApp 기능에 대한 액세스를 허용하거나 허용하지 않습니다
** ShowCompanyNameInTitle: True/False - 회사 이름이 표시되는지 여부를 나타냅니다


* 다음 항목을 c:\Program Files (x86)\Cloud Workspace에 추가할 수 있습니다.
+
** banner.jp g, banner.png, banner.gif 또는 banner.bmp 이 클라이언트 창에 표시됩니다.
** 이러한 영상은 21:9 비율로 되어 있어야 합니다






=== 버그 수정

* 등록된 기호가 조정되었습니다
* 도움말 페이지의 빈 전화 및 이메일 항목이 수정되었습니다

