= CWMS 5.1 마이너 릴리스: 2018년 10월 18일 목요일



NOTE: CWMS v5.1 릴리스 시 더 이상 반복되는 릴리스는 없으며, 모든 릴리스는 핫픽스로 간주됩니다.



== CWMS 5.1 마이너 릴리스: 2018년 10월 18일 목요일

구성 요소: 5.1 Cloud Workspace Management Suite 언제: 2018년 10월 18일 목요일, 오후 10시~오후 11시 동부 지역 영향: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스가 중단 없이 유지됩니다. Cloud Workspace Management Suite에 대한 액세스는 계속 사용할 수 있습니다.



=== 작업 공간 관리 제품군

* 응용 프로그램 테이블에 검색 기능을 추가합니다
* 응용 프로그램 테이블의 정렬 기능이 향상되었습니다




== CWMS 5.1 마이너 릴리스: 목요일, 2018년 9월 6일

구성 요소: 5.1 Cloud Workspace Management Suite 언제: 목요일, 2018년 9월 6일 오후 10시~오후 11시 동부 지역 영향: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스가 중단 없이 유지됩니다. Cloud Workspace Management Suite에 대한 액세스는 계속 사용할 수 있습니다.



=== 5.1 Cloud Workspace Management Suite

* 사용자 지정 앱 카탈로그에서 하위 파트너를 검색할 수 있는 기능이 추가되었습니다
* Data Center 모듈에서 화면을 새로 고치면 오류 프롬프트가 발생하는 버그를 수정했습니다
* 최대 폴더 이름 크기 제한을 제거하여 폴더를 보다 쉽게 찾을 수 있습니다
* VM의 리소스 수가 지정된 최소 CPU 및 RAM 값보다 낮아서는 안 됩니다




=== 5.1 Cloud Workspace 툴 및 서비스

* 이메일을 선택한 사용자가 코드를 받지 못하는 MFA 버그 수정
* 사용자 수 리소스 할당 유형에 대해 추가 CPU 및 RAM을 입력할 수 있습니다
* 경우에 따라 필요한 서버 수가 꺼져 있는 서버 로드 할당 유형에 대한 리소스 할당 버그의 수정
* 서버를 자동으로 재부팅할 때 보호 추가 – CwVmAutomationService가 사용 중이면 20분 후에 다시 시도하십시오
* CWMGR1에 와일드카드 인증서 설치 처리 개선
* 데이터 센터 리소스 보고서의 고정 데이터
* RAM 리소스 업데이트 처리 개선
* 사용 가능한 하드 드라이브 리소스에 대한 계산 기능이 향상되었습니다
* CPU 제품군을 설정할 수 있도록 v4의 ProfitBrick' API에 대한 지원을 제공합니다
* 프로비저닝 컬렉션을 생성할 때 사용되는 ProfitBrick의 이전 임시 템플릿 삭제 수정
* VM을 생성하기 위해 ProfitBrick의 하이퍼바이저를 기다리는 동안 시간 초과가 증가했습니다
* 새 버전의 VdcTools를 설치할 때 VdcToolsVersionRunningAtVdc가 진행되는 즉시 업데이트하여 자동화를 더욱 빨리 실행합니다
* RDP 게이트웨이 서버에 와일드카드 인증서를 설치할 때 발생하는 버그를 수정했습니다
* FTP 서버에 와일드카드 인증서의 이전 수동 설치를 자동화합니다
* 암호 만료 알림이 사용자에게 암호를 업데이트할 것을 강요하지 않는 버그를 수정했습니다
* 알 수 없는 사용자 오류 발생 빈도를 줄이기 위해 파일 감사 프로세스가 개선되었습니다
* 파일 감사 보고서가 폴더를 적절하게 제외하지 못하는 버그를 수정했습니다
* 연결 브로커의 인증서가 만료된 경우 와일드카드 인증서를 설치하는 기능이 추가되었습니다
* 시작 폴더에서 암호 만료 알림 바로 가기를 제거한 경우(다시 설치함) 암호 만료 알림이 나타나지 않는 버그 수정
* 사용자가 로그인한 경우 와일드카드 인증서가 HTML5 포털 서버의 업데이트를 지연시키지 않는 버그를 수정했습니다
* 와일드카드 인증서가 이미 최신 상태일 때 HTML5 포털 서버를 업데이트해야 하는 것으로 보이는 버그를 수정했습니다
* 연결 브로커 서버에 와일드카드 인증서를 설치할 때 발견된 버그를 수정했습니다
* 로컬 VM 계정이 제거된 클론 생성 문제를 해결했습니다
* 클론 서버가 테넌트를 마이그레이션 모드로 전환하는 문제 해결
* 하이퍼바이저가 VM을 생성하는 데 예상보다 오래 걸리는 vCloud의 VM 클론 생성 오류를 수정했습니다
* AzureRM에서 VM을 삭제하면 연결된 관리 디스크도 항상 삭제되는 버그를 수정했습니다
* 두 빌드 작업이 겹치지 않도록 AzureRM에서 VM을 생성하는 드문 타이밍 문제를 해결했습니다
* AzureRM의 시스템 크기 및 유형 목록이 업데이트되었습니다
* 배포하는 동안 GCP용 하이퍼바이저에서 서브넷을 구성할 때 오류가 해결되었습니다
* 모니터링 데이터 저장 오류 수정: 서버가 사용 중일 때 데이터가 기록되지 않도록 시간 제한을 제거하여 플랫폼 상태 수정
* 각 서버가 표준 시간대를 개별적으로 설정하거나 플랫폼 자동화를 통해 제어하지 않도록 하는 기능이 추가되었습니다
* 보조 사이트에서 VM을 생성할 때 기본 사이트에서 정적 IP 주소를 반환하는 버그를 수정했습니다
* 사용자 로그인 보고서의 사용자 이름을 캡처하는 중 오류가 해결되었습니다
* 시간 초과가 발생하지 않도록 호출 비동기식으로 만들어 이전 모니터링 데이터를 삭제하지 못한 버그를 수정했습니다
* 모든 인프라 서버에 와일드카드 인증서를 자동으로 설치합니다




== CWMS 5.1 마이너 릴리스: 목요일, 2018년 7월 12일

구성 요소: 5.1 CWMS 툴 및 서비스 기간: 2018년 7월 12일 목요일 @ 10-10:30 pm 동부 영향: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스가 중단 없이 유지됩니다.



=== 5.1 CWMS Web App

* Global App Catalog 설정 지속성과 관련된 문제를 해결합니다




== CWMS 5.1 마이너 릴리스: 목요일, 2018년 5월 17일

구성 요소: 5.1 CWMS 도구 및 서비스 언제: 2018년 5월 17일 목요일 @ 10-11시 EST 영향: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스가 중단 없이 유지됩니다.



=== 5.1 CWMS Web App

* 앱 서비스 그룹의 사용자 요약과 관련된 문제를 해결합니다
* 데이터 센터 마법사에서 사용자 이름 및 암호를 미리 채우는 문제를 해결합니다
* 데이터 센터 마법사에서 로컬 VM 관리자 및 레벨 3 기술자에 대한 사용자 이름 유효성 검사를 추가합니다
* 세션 시간 초과 후 사용자 자동 로그아웃을 포함하여 세션 처리 기능이 향상되었습니다
* 기본 관리자를 찾을 수 없는 경우 Admins를 삭제할 때 발생하는 문제를 해결합니다
* 데이터 센터의 자리 표시자 변경 -> 프로필 서버 변경 프로파일 이름 입력 에서 프로파일 입력 으로 변경하고 프로파일 이름 에서 서버 이름 으로 레이블을 변경합니다
* 비 클라우드 작업 영역 사용자에 대해 AD 관리자가 작동하지 않도록 설정 수정
* 비 Cloud Workspace 고객에 대한 새 사용자/그룹을 추가하지 못하도록 JavaScript 오류 수정
* 마스터 파트너가 하위 파트너를 위한 Active Directory 사용자 관리자를 생성할 수 있도록 허용합니다
* 하위 파트너의 기본 관리자의 암호 재설정이 잘못되는 버그를 수정합니다




== CWS 5.1 업데이트 릴리스: Wed., 2월 2018년 21일

구성 요소: 5.1 CW 도구 및 서비스 시기: Wed., 2월 2018년 10월 11일 EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다.



=== 5.1 CW 웹 앱

* 관리자 액세스 역할을 통해 사용자 폴더 관리 문제를 해결합니다




=== 5.1 CW 도구 및 서비스

* 작업 공간으로 "서비스 없음" 클라이언트를 업그레이드할 때 실패한 서버가 자동으로 삭제되지 않도록 합니다
* W2016 GPO 업데이트를 처리하여 W2016 VM의 RDS 세션에 로그인한 사용자가 알림 팝업을 잠시 볼 수 없도록 합니다




=== 5.1 REST API

* 핵심 라이선스 기반 앱(특히, SQL)을 보다 효율적으로 처리하기 위해 새 특성 추가(새 특성을 사용하도록 CWS의 SPLA 보고서 수정)




== CWS 5.1 업데이트 릴리스: Wed., 2월 2018년 7월 7일

구성 요소: 5.1 CW 도구 및 서비스 시기: Wed., 2월 2018년 7월 10일~11시 EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다.



=== 5.1 CW 웹 앱

* 없음




=== 5.1 CW 도구 및 서비스

* Windows 2016에서 App Locker 비활성화 문제 해결(새로 발견된 내부 Windows 2016 문제)
* 클론 장애 이벤트를 기준으로 IP가 잘못 재할당되는 경우 버그를 수정합니다




=== 5.1 REST API

* Provisioning Collection에서 서버를 수정할 때 저장 저장소 유형을 수정합니다
* TS(터미널 서버) 서버 두 대를 사용하여 프로비저닝 수집을 생성할 때는 수집을 검증하기 위해 TS 서버 한 대만 빌드해야 합니다




== CWS 5.1 부 릴리스: Wed., 1월 2018년 1월 31일

구성 요소: 5.1 CW 도구 및 서비스 시기: Wed., 1월 31, 2018 @ 10-11 pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단되지 않습니다.



=== 5.1 CW 웹 앱

* 최상위 CWS 모듈의 테이블당 행 수를 10개에서 20개로 늘립니다
* 사용자 지원 전용 관리 수정 클라이언트를 자세히 살펴볼 수 없습니다




=== 5.1 CW 도구 및 서비스

* 템플릿에 .Net Framework v4.5.2가 없는 경우 서버 생성에 오류가 발생할 때 버그를 수정하십시오
* Hyper-V에서 VM 클론 생성 시 문제 해결




== CWS 5.1 부 릴리스: Wed., 1월 2018년 10월 10일

구성 요소: 5.1 CW 도구 및 서비스 시기: Wed., 1월 10, 2018 @ 10-11 pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다.



=== 5.1 CW 도구 및 서비스

CWS 버전 5.1 도구 및 서비스(CW 자동화 서비스, VM 자동화 서비스 및 CWAgent 서비스 포함)가 업데이트되어 특정 RemoteApp 응용 프로그램 전달 시나리오에서 발생하는 모든 인증 오류를 제거합니다. 특히 서비스는 다음과 같이 수정됩니다.

* 세션 서버에 대한 SSL 와일드카드 인증서의 자동 배포를 원격 데스크톱(RD) 연결 브로커 서버 및 고급 사용자 서버에만 배포하도록 변경합니다. 비 브로커 세션 서버는 RDS(원격 데스크톱 서비스)에서 생성된 기본 인증서를 사용합니다.
* SDDC에서 Active Directory의 외부 DNS 정방향 조회 영역을 변경하여 클라이언트 공유 세션 서버에 대해 하나의 DNS 레코드만 만듭니다. 이 레코드는 클라이언트의 RDS 브로커 서버(VM)를 가리키며, 이 서버는 공유 세션 서버 간의 로드 밸런싱을 처리합니다. 고급 사용자 서버는 계속해서 별도의 DNS 항목을 갖습니다.


참고: 여러 공유 세션 서버를 사용하는 최종 클라이언트 구성만 이 문제의 영향을 받았으나 이 구성을 사용하여 신규 및 수정된 클라이언트 구성이 배포됩니다.



== CWS 5.1 부 릴리스: Wed., 1월 2018년 3월

구성 요소: 5.1 CW 웹 응용 프로그램 시기: Wed.., 1월 3, 2018 @ 10 - 10:30 pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단되지 않습니다.



=== 5.1 CW 웹 앱

* CWS 작업 영역 모듈에서 회사 코드별로 정렬을 수정합니다
* 클라우드 작업 영역 사용자 수정 -> 암호 강제 재설정(변경 내용을 저장하지 않음)(다른 모듈로 이동한 다음 다시 사용자로 이동 시)
* SDDC 자체 구축 마법사: ThinPrint 설치 선택을 취소하면 확인 경고 모달 추가(라이센스 섹션)




== CWS 5.1 마이너 릴리스: 화요일, 12월 2017년 5월 5일

구성 요소: 5.1 CW Web App when: Tues., 12월 5, 2017 @ 10 - 10:30 pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다.



=== 5.1 CW 웹 앱

* Internet Explorer(IE) 11에서 CWS 관리자 MFA 오류를 수정합니다
* CWS 그룹 수정 -> 로컬 드라이브 액세스('찾을 수 없음'이 반환됨)
* 데이터 센터 자체 배포 마법사: AzureRM(ARM) Azure Active Directory에 대한 지원을 추가합니다
* 응용 프로그램 카탈로그: 구독 옵션이 항상 사용 가능/전파되는지 확인합니다
* CWS 스크립트된 이벤트 모듈 > 스크립트 활동 -> 응용 프로그램 추가: 잘못된 응용 프로그램 아이콘 경로 수정
* 관리 액세스 요청의 효율성을 개선하여 CWS v5.0으로 리디렉션할 때 오류를 방지합니다
* AppService 세부 정보를 업데이트하거나 AppService에 대한 애플리케이션 라이센스를 관리할 때 다양한 오류를 수정합니다
* CWS 작업 공간 모듈 > 작업 공간 추가 마법사 -> AppServices 수정 전역 컨트롤 플레인으로 전송되는 형식이 잘못되었습니다
* CWS 작업 공간 모듈 > 작업 공간 추가 마법사 -> 새 클라이언트 -> 3단계, 업데이트 그룹을 수정하여 업데이트가 처리되도록 JavaScript 오류를 해결합니다




== CWS 5.1 마이너 릴리스: 2005년 11월 2017년 11월 11일

구성 요소: 5.1 CW 웹 응용 프로그램 시기: 토요일, 11월 2017년 11월 11일 @ 10-11pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다.



=== 5.1 CW 웹 앱

* 11월 오후 10시(EST) 기준 11 모든 CWS 5.1 파트너는 을 사용해야 합니다 https://iit.hostwindow.net[]. 이 URL은 CWS 5.1(및 CWS 5.0)을 지원하기 위해 개보수 중입니다. 파트너는 CWS Admin Access를 사용하는 CWS 관리자와 최종 사용자가 이러한 변경 사항을 인지하도록 할 책임이 있습니다.




== CWS 5.1 마이너 릴리스: 월, 10월 2017년 30일

구성 요소: 5.1 CW 웹 응용 프로그램 및 5.1 CW 도구 및 서비스 시기: 월, 10월 2017년 10월 30일 @ 10-11pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단 없이 유지됩니다



=== 5.1 CW 웹 앱

* CWS 관리자 MFA: MFA용 제출 코드 입력 을 누르고 MFA 코드 재전송을 방지하는 버그를 수정합니다
* SDDC 셀프 구축 마법사: GCP의 경우, 비활성화만 하는 대신 로컬 VM 이름에 대한 관리자가 있습니다
* SDDC 자체 구축 마법사: 시간대에 대한 드롭다운 폭 증가
* 스크립트 이벤트: 스크립트 작업에 인수 필드를 추가합니다
* 스크립트 이벤트: 스크립트 이벤트 스크립트의 런타임 변수로 %ApplicationName%을(를) 추가합니다




=== 5.1 CW 도구 및 서비스

* 최종 사용자 이메일 주소: 기존 최종 사용자의 이메일 주소가 DB에 저장되지 않는 문제를 해결합니다
* 최종 사용자 로그온 상태: 최종 사용자의 UPN을 가져오는 문제를 해결합니다
* AzureRM의 최종 사용자 로그온 상태: Azure 관리 디스크 지원
* 템플릿: 템플릿이 제대로 삭제되지 않을 경우 워크플로를 수정하십시오
* 리소스: 기존 리소스 풀을 새 할당 유형으로 변환하는 문제 해결
* 파일 감사 보고서: 사용자를 알 수 없는 버그를 수정합니다
* Windows 2016: GPO가 최종 사용자 작업 공간에서 PowerShell 아이콘을 제거하도록 수정되었습니다
* 자원 변경/자원 할당 보고서: 오류 수정이 잘못 표시됩니다
* 데이터 센터 리소스 보고서: 하이퍼바이저가 사용 가능한 하드 드라이브 공간 또는 VM 견적을 반환하도록 구성되지 않은 경우 보고서에 오류가 표시되지 않도록 합니다
* 인프라 서버 월별 재부팅: 이 서버가 재부팅 중이어서 인프라 서버가 CWMGR1 서버와 통신할 수 없기 때문에 계획대로 매월 재부팅되지 않는 상황을 해결합니다




== 5.1 마이너 릴리스: 화요일, 10월 2017년 3월 3일

구성 요소: 5.1 CW 웹 응용 프로그램 및 5.1 CW 도구 및 서비스 언제: 화요일, 10월 3, 2017 @ 10 - 11pm EST Impact: 최종 사용자를 위한 Cloud Workspace 데스크톱 및 애플리케이션 서비스에 대한 액세스는 중단되지 않습니다



=== 5.1 CW 웹 앱

* AppServices: AppService 응용 프로그램에 대한 추가 라이센스 기능을 차단하는 문제 해결
* AppServices: AppService 응용 프로그램에 항상 "새 인스턴스 추가" 기능을 사용할 수 있는지 확인합니다
* 리소스 풀 용어: 용어가 업데이트되지만 변경 사항이 없는 경우에도 서버에 리소스 풀 구성을 적용할 수 있습니다. "업데이트"가 "서버에 적용"으로 변경되고 "편집"이 "관리"로 변경되었습니다.
* 워크로드 일정: 편집 모달이 항상 열려 있는지 확인합니다
* 워크로드 일정: 시간을 선택할 수 있는 화살표가 항상 표시되는지 확인합니다
* 스크립팅된 이벤트: 보다 세부적인 시간 선택이 가능합니다
* CWS 보고서 'Admin Access': IP 열에 클라이언트 IP가 아닌 여러 IP 주소가 나열되는 문제를 해결합니다




=== 5.1 CW 도구 및 서비스

* 파일 감사 서비스: 이제 일관되게 비활성화되었습니다
* 자동화 서비스 및 새로운 SSL 와일드카드 인증서(RDP 연결): RDS 게이트웨이에서 업데이트된 RDP 인증서가 항상 새로 고쳐지도록 명령 순서를 업데이트합니다(예: 캐시되지 않음).




== CWS ® 5.1 초기 릴리즈 개요

Cloud Workspace Suite 5.1은 현재 2017년 3분기부터 퍼블릭 베타를 진행 중입니다. 이 릴리스에는 CWS API 및 관리 제어 인터페이스 업데이트가 모두 포함되어 있습니다. 이 릴리스는 CWS 5.0(2016년 4분기 출시)에 대한 업데이트이며 버전 4.x 엔터티에 대한 "이전 버전과 호환되지 않습니다."

2017년 4분기에 공식적으로 출시되면 CWS 5.1로 전환하는 데 필요한 업그레이드 비용 또는 구현 비용이 없습니다. CloudJumper는 각 파트너와 공동으로 업그레이드를 완료할 것이며 기존 서비스를 중단하지 않을 것입니다. CWS 5.1은 이전 버전의 모든 기능을 계속 지원하고 관리자 및 최종 사용자 환경을 모두 향상시키는 새로운 기능을 확장하며, 이전의 Cloud Workspace Suite 릴리스에 도입된 수상 경력에 빛나는 자동화 및 오케스트레이션을 더욱 향상시킵니다.

CWS 5.1 업그레이드는 CWS 5.0에 도입된 업데이트된 아키텍처 및 REST API 플랫폼을 확장하고 활용함으로써 가장 빠르고 쉬운 업그레이드입니다. CWS 5.1은 보다 친숙한 환경을 위한 CloudJumper의 약속을 지속하여 외부 개발자가 Cloud Workspace를 기반으로 서비스와 제품을 확장할 수 있도록 합니다.


NOTE: CWS 4.x는 2017년 12월 31일에 공식 수명 종료 기간이 종료됩니다. CWS 4.x 플랫폼에 남아 있는 파트너는 더 이상 4.x 배포에 대한 직접적인 지원을 받지 않으며 4.x 업데이트나 버그 수정은 더 이상 제공되지 않습니다.



=== 5.1 주요 내용:

* Windows 2016 Server에 대한 지원
* Microsoft Azure Resource Manager에 대한 전체 스택 지원
* Office 365 단일 인증 지원
* CWS 포털 관리자를 위한 MFA
* 프로비저닝 수집 관리 기능 향상
* 관리자가 정의한 자동화 및 스크립트
* 리소스 크기 조정 관리 구성표




==== Windows 2016 Server에 대한 지원

* 지원되는 모든 플랫폼에 대해 Windows Server 2016 서버 버전을 지원합니다.
* Windows 2016 Server는 공유 RDS 세션 사용자를 위한 "Windows 10" 데스크톱 환경을 제공하며 그래픽 집약적 응용 프로그램을 위한 GPU 할당 등의 구성 옵션을 활성화합니다.




==== Microsoft Azure Resource Manager의 전체 스택 지원

* Microsoft는 기존 암호화 키/위임된 계정 사용자 권한 모델에서 Azure Resource Manager 모델로 마이그레이션해야 합니다.
* Microsoft Azure Resource Manager는 사용자가 솔루션 내의 리소스를 그룹으로 사용할 수 있도록 하는 프레임워크입니다.
* 필요한 인증 속성은 SDDC(소프트웨어 정의 데이터 센터) 배포 중에 한 번 수집된 다음 다시 입력하거나 다시 인증할 필요 없이 다른 Microsoft Azure 작업에 다시 사용됩니다.




==== Office 365 단일 인증 지원

* Microsoft Office 365는 최종 사용자가 새 컴퓨터 또는 장치에서 Office 생산성 제품군을 사용할 때마다 자격 증명을 입력해야 하는 인증 모델을 사용합니다.
* CWS 5.1은 서버 팜 전체에서 이러한 자격 증명을 관리하므로 최종 사용자는 새 Office 365 구독을 처음 사용할 때만 인증을 받아야 합니다.




==== 프로비저닝 수집 관리 기능 향상

* 미리 정의된 워크로드를 위한 하이퍼바이저 템플릿의 구성 및 관리는 특히 여러 하이퍼바이저 플랫폼에서 작업할 때 혼란스러울 수 있습니다.
* CWS 5.1은 기존 템플릿 또는 클라우드 공급자 VM 이미지를 기반으로 서버 인스턴스를 생성하고 CWS Web App에서 애플리케이션을 설치하기 위해 생성된 서버에 직접 연결/로그인하는 기능을 포함하는 자동화된 하이퍼바이저 관리 기능을 도입했습니다. 구성된 서버 인스턴스에서 자동 템플릿 생성/Windows sysprep, 그리고 CWS 내에서 애플리케이션 경로 및 설치의 검증을 통해 하이퍼바이저 또는 클라우드 서비스 대시보드에 직접 액세스할 필요가 없습니다.




==== CWS 포털 관리자를 위한 MFA

* CWS 5.1에는 CWS 관리자만 사용할 수 있는 MFA(다중 요소 인증) 솔루션이 내장되어 있습니다
* 파트너는 최종 사용자를 위해 자체 MFA 솔루션을 구현할 수 있습니다. Duo, Auth-Anvil, Azure MF 등 다양한 옵션이 제공됩니다. CloudJumper는 2018년 1분기에 최종 사용자를 위해 자체 내장형 MFA를 출시할 예정입니다




==== 관리자가 정의한 자동화

* CWS는 관리자가 정의한 작업/스크립트 실행 자동화를 통해 서비스 공급자를 위한 향상된 배포/관리 자동화를 제공합니다.
* 이러한 향상된 기능을 통해 CWS 5.1은 구축 속도를 크게 높이고 관리를 단순화하며 오버헤드 비용을 절감할 수 있습니다.
* CWS Administrator Defined Automation을 사용하면 이벤트를 기반으로 응용 프로그램을 설치 또는 업그레이드할 수 있으므로 파트너가 이 방법을 사용하여 자동화된 응용 프로그램 설치/유지 관리를 트리거할 수 있습니다.




==== 리소스 사이징 관리 체계

* CWS 5.1 리소스 기능은 리소스 스키마를 3개 더 추가하여 리소스를 동적으로 확장할 수 있는 기능을 향상시킵니다
* 기존의 총 사용자 스키마는 이제 세 가지 더 많은 리소스 사이징 구성인 고정, 활성 사용자 및 활동 기반 으로 보강되었습니다
* 예: 고정 방법은 CPU 및 RAM의 정확한 사양을 지원합니다.
* 모든 리소스 크기 조정 스키마는 즉시/강제 변경 또는 야간 자동 자원 확인/수정을 계속 허용합니다.

