= 애플리케이션 설치/제거 작업을 추가합니다




=== 애플리케이션 설치/제거 작업을 추가합니다

리포지토리의 스크립트에서 작업을 수행하기 위해서는 해당 스크립트를 선택한 트리거와 연결하기 위한 작업을 만들어야 합니다. 이 예에서는 vDS의 _Workspace > Applications_PAGE에서 앱을 작업 공간에 추가하거나 작업 영역에서 제거할 때 이 응용 프로그램을 설치/제거합니다.

vDS 스크립트 이벤트는 _Application Install_(또는 _Application Uninstall_) 이벤트 유형의 대안으로 사용할 수 있는 _Create Server_와 같은 다양한 유형의 활동 트리거를 제공합니다. Create Server _ 을(를) 사용하면 VDS에서 새로 생성된 모든 VM에 대해 이 앱 설치를 실행할 수 있습니다. _Create Server_ 및 기타 트리거는 문서화되어 있으며 탐색할 수 있습니다 link:Management.Scripted_Events.scripted_events.html["여기"].


NOTE: 이 응용 프로그램은 VDS 응용 프로그램 라이브러리에 있어야 합니다. 여기 link:Management.Applications.application_entitlement_workflow.html#add-applications-to-the-app-catalog["섹션을 참조하십시오"] RDS의 앱 소유 권한 문서에서 라이브러리에 앱을 추가하는 방법에 대해 설명합니다.

.활동을 생성하고 이 스크립트를 작업에 연결하려면:
. VDS에서 _Scripted Events_섹션으로 이동합니다
. Activities_에서 _ + Add Activity _ 를 클릭합니다
. 열린 대화 상자 창에서 다음 정보를 입력합니다.
+
** * 이름: * 이 활동의 이름을 지정합니다
** * 설명: * 선택적으로 설명을 입력합니다
** * 배포 * 드롭다운에서 원하는 배포를 선택합니다
** * 스크립트: * 드롭다운에서 설치(또는 제거) 스크립트를 선택합니다. 이는 클론 복제 및 사용자 지정한 글로벌 스크립트 또는 고객 스크립트일 수 있습니다.
** 인수: * 공란으로 남겨 둡니다
** 사용 확인란: * 확인란을 선택합니다
** 이벤트 유형: * 드롭다운에서 '응용 프로그램 설치'(또는 응용 프로그램 제거)를 선택합니다
** * 응용 프로그램: * 드롭다운에서 이 응용 프로그램을 선택합니다
** * 바로 가기 경로: * 이 응용 프로그램의 기본 바로 가기 경로를 입력합니다(위에 표시됨).



