= 개요
:allow-uri-read: 




== 개요

응용 프로그램 오류 문제 해결은 VDS 자체는 포함하지 않지만 VDS 및 관리자에게 제공하는 제어 수준에 의해 크게 도움이 되는 일반적인 관리 방법입니다. NetApp VDS는 고객에게 이러한 문제를 해결하지 않지만, NetApp의 경험을 통해 관리자는 다음과 같은 몇 가지 기본 정보를 식별하여 최종 사용자 및/또는 타사의 세부 정보를 확인하고 문제를 해결할 수 있습니다.

* 문제가 발생한 사용자의 이름입니다
* 사용자가 작업 중인 애플리케이션의 이름입니다
* 사용자의 세션이 있던 서버입니다
* 문제를 재현하는 단계입니다




== 도구 검토



=== 모니터링

사용자가 사용 중인 서버를 확인한 후 모니터링 솔루션을 확인하여 리소스(CPU 및 RAM) 사용량이 정상 레벨 내에 있는지 확인합니다. 또한 응용 프로그램별 요구 사항(실행되지 않을 경우 문제를 일으키는 특수 서비스)이 작동하는지 확인할 수 있습니다. 이와 같은 상황에서는 해당 서비스의 상향/하향 모니터링과 같은 고급 설정이 트리거되었을 수 있습니다.



=== 안티바이러스

서버와 Azure Active Directory에 모두 액세스할 수 있는 관리자는 검색된 내용과 설정된 정책을 검토할 수 있습니다. 예기치 않은 상황이 발생하면 응용 프로그램에 영향을 줄 수 있습니다.



=== 추가 도구

일부 응용 프로그램에는 무한정 로그인 상태를 유지하는 서비스 계정 또는 물리적 장비(예: 현장 네트워크 어플라이언스 또는 제조 장비 또는 진단 유틸리티)에 대한 VPN 같은 추가 구성 요소가 필요합니다. 이러한 경우 응용 프로그램 특정 오류는 응용 프로그램이 설치된 방식 또는 해당 설정이 구성된 방식 이외의 다른 원인으로 인해 발생할 수 있습니다.



=== 제3자에 대한 액세스 확장

애플리케이션 및/또는 해당 데이터베이스는 소프트웨어 구성, 관리 및 통합에 대한 소프트웨어 공급업체(ISV) 자체 또는 타사 전문가가 설치, 구성 및 지원하는 경우가 많습니다. 이러한 경우 임시 관리 액세스 권한을 다음 단계로 확장하려고 합니다. link:Management.System_Administration.provide_3rd_party_access.html["제3자에 대한 임시 액세스 제공"]

업그레이드 또는 업데이트가 완료된 후 또는 문제가 해결된 후에 이러한 타사 계정을 종료하는 것이 좋습니다.

대부분의 경우 이러한 수준의 문제 해결을 위해서는 ISV와 소프트웨어 유지 보수 계약을 체결해야 합니다. 그렇지 않으면 ISV가 이를 지원할 수 없습니다.


NOTE: 또한 문제 해결 문제가 하드웨어(데스크톱, 노트북 컴퓨터, 씬 클라이언트 등) 최종 사용자와 관련이 있을 수 있습니다. 예를 들어, 사용자의 랩톱을 업그레이드하면 씬 클라이언트 구성 파일의 눈에 시스템을 잠글 수 있습니다. 즉, 최종 사용자는 가상 데스크톱에 로그인할 수 있는 도구에 액세스할 수 없습니다. 이 경우 제조업체가 지원을 제공하기 전에 하드웨어 유지보수 계약이 필요할 수 있습니다.
