= 개요




== 개요

Management.command_center.operations.add_existing_server_to_company.adoc Management.command_center.operations.backup_server_now.adoc /toinclude/todo/Management.command_center.operations.allow_new_AVD_connections.adoc_Management.command_center.operations.change_data_home_pro_folders.adoc include/todo Management.command_center.operations.change_password.adoc/Management.command_center.operations.backup_list.adoc Management.command_center.operations.create_server_from_backup.adoc_include/todo Management.command_center.operations.create_server_from_clone.adoc_Management.command_center.operations.install_notepad++_Chrome.adoc /Management.command_center.operations.create_server_from_template.adoc todo_include Management.command_center.operations.create_template_phase_1.adoc/todo Management.command_center.operations.create_template_phase_3.adoc_Management.command_center.operations.list_drives_for_server.adoc /todo_include Management.command_center.operations.created_company.adoc/Management.command_center.operations.backup_restore_to_drive.adoc Management.command_center.operations.delete_backup.adoc /todo_include/Management.command_center.operations.install_thinprint_license_server.adoc_Management.command_center.operations.delete_datacenter_site.adoc include/todo Management.command_center.operations.delete_drives_from_server.adoc_include Management.command_center.operations.delete_server.adoc/Management.command_center.operations.backups_run_all_scheduled.adoc /Management.command_center.operations.delete_template.adoc todo_include Management.command_center.operations.edit_provisioning_collection.adoc/todo_Management.command_center.operations.create_cache_company.adoc /Management.command_center.operations.edit_resource_pool.adoc todo_include Management.command_center.operations.edit_workload_schedule.adoc/Management.command_center.operations.create_azure_file_share.adoc Management.command_center.operations.exclude_server_from_monitoring.adoc_todo Management.command_center.operations.expand_drive.adoc_include/Management.command_center.operations.file_migration.adoc todo_Management.command_center.operations.create_azure_netapp_files_share.adoc /Management.command_center.operations.generate_email_reports.adoc Management.command_center.operations.generate_reports.adoc /todo_include/todo_include/todo_Management.command_center.operations.create_data_center_site.adoc /Management.command_center.operations.list_long_running_operations.adoc_include/todo_include/todo_include/todo_Management.command_center.operations.create_no_server_company.adoc_include/todo_Management.command_center.operations.copy_template_to_gallery.adoc Management.command_center.operations.load_active_users.adoc Management.command_center.operations.load_cache_companies.adoc Management.command_center.operations.load_hypervisor_config_options.adoc Management.command_center.operations.load_hypervisor_type.adoc Management.command_center.operations.load_machine_series.adoc Management.command_center.operations.load_machine_sizes.adoc Management.command_center.operations.load_max_concurrent_users.adoc Management.command_center.operations.load_resource_pool_data.adoc Management.command_center.operations.load_server_resource_report_data.adoc Management.command_center.operations.load_servers_for_company.adoc Management.command_center.operations.load_storage_types.adoc Management.command_center.operations.load_templates.adoc Management.command_center.operations.load_virtual_machines.adoc Management.command_center.operations.make_server_active.adoc Management.command_center.operations.reboot_server.adoc /toinclude/todo/Management.command_center.operations.make_server_data_server.adoc_include/todo/Management.command_center.operations.migrate_company.adoc_Management.command_center.operations.reload_configuration.adoc include/todo_Management.command_center.operations.reload_monitored_applications.adoc Management.command_center.operations.run_daily_maintenance.adoc /todo Management.command_center.operations.remove_vds_software.adoc_include Management.command_center.operations.set_gateway_address.adoc/todo_Management.command_center.operations.run_program.adoc /todo_Management.command_center.operations.set_time_zone.adoc include/Management.command_center.operations.move_servers_to_company.adoc_Management.command_center.operations.should_pool_be_running.adoc include/todo_Management.command_center.operations.run_daily_actions.adoc /todo Management.command_center.operations.start_company.adoc_include Management.command_center.operations.start_server_for_wake_on_demand.adoc/todo_Management.command_center.operations.run_resource_allocation.adoc /todo_include Management.command_center.operations.start_server.adoc/Management.command_center.operations.resource_allocation_enable.adoc /Management.command_center.operations.stop_company.adoc todo_include Management.command_center.operations.stop_cwagent.adoc/todo_Management.command_center.operations.rename_server.adoc_include Management.command_center.operations.stop_sddc.adoc/todo_Management.command_center.operations.run_workload_schedule.adoc /todo_include Management.command_center.operations.stop_server.adoc/Management.command_center.operations.set_external_dns.adoc Management.command_center.operations.test_hypervisor_connection.adoc Management.command_center.operations.update_active_user_count.adoc Management.command_center.operations.update_cw_vm_automation_service.adoc Management.command_center.operations.wildcard_cert_create_new.adoc Management.command_center.operations.wildcard_cert_install.adoc
